### ISSUE TITLE
fetch ResultSet based on override equals()

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#101]
@npgall 

I want to go through a collection and fetch all objects that are equal, is it possible? I also need this to work even if used on `Bar` which is an extension of `Foo` in this case.

i.e.
```
public static final Attribute<Foo, Foo> FOO_INDEX = new SimpleAttribute<Foo, Foo>() {
        @Override
        public Foo getValue(Foo foo, QueryOptions queryOptions) {
            return foo;
        }
    };
```

```
ResultSet<Foo> resultSet = foos.retrieve(QueryFactory.equal(Foo.FOO_INDEX, foo));
```

I believe the `ResultSet` object functions similar to a `HashSet` in that no duplicates may exist so I'm assuming the above would not be possible?

It seems like my `equals(...)` method is being passed objects with values that have been converted `toLowerCase()` which is making it difficult for me to compare equality of objects. Is this being done somewhere before executing `equals(...)` i.e. after calling `IndexedCollection.add(obj)`?

What's even more confusing is that when my `equals(...)` method returns `true` after calling `add(obj)` then the object gets added to the `IndexedCollection` anyway

Can you please clarify what `add(obj)` is actually doing here? Also, can you please comment on how uniqueness is maintained in `IndexedCollection`? Is it via my `equals(...)`? If so, what is run in the background and in what order - like which objects are compared and how?

Steps to Reproduce:

1. Create a new class `Foo` with just one field; `name`
2. Override `equals(...)` to `return foo.getName().equals(other.getName());`
3. Create three instances of `Foo` using names: `test`, `TEST`, `test`
4. Add all three instances of `Foo` to `IndexedCollection`
5. List contents of `IndexedCollection`
6. Two instances are returned when it should only return one, the first one added to the collection

**Comment by bluedoo** [comment]
@npgall Any ideas?

**Comment by npgall** [comment]
Hi bloodoo,

The IndexedCollection is an implementation of `java.util.Set` and it complies with the specifications of that interface. Yes indeed, uniqueness is maintained via the implementation of `equals()` and `hashCode()` in the objects added to the collection (i.e. your implementations of those methods if you overrode them).

You might be running into strange issues here if you only overrode the `equals()` method, without overriding `hashCode()` though? To avoid strange behavior, you need to implement both. See the general contract of [hashCode()](http://docs.oracle.com/javase/6/docs/api/java/lang/Object.html#hashCode%28%29), in particular: 

* _"If two objects are equal according to the equals(Object) method, then calling the hashCode method on each of the two objects must produce the same integer result."_

...CQEngine won't convert strings to lowercase - the issue is probably caused by `hashCode()` inconsistency above.

The ResultSet is not an implementation of `Set` per-se - it's just an interface to access results, which are usually retrieved from the collection on-the-fly. In fact it can return duplicates by default, although it's configurable (see [DeduplicationStrategies.md](https://github.com/npgall/cqengine/blob/master/documentation/DeduplicationStrategies.md)).

Anyway, yes you can retrieve all objects which are equal to a given object!
The key is to use QueryFactory.selfAttribute() as follows:

```java
import static com.googlecode.cqengine.query.QueryFactory.*;
...
Foo foo = // some instance of Foo
ResultSet<Foo> resultSet = foos.retrieve(equal(selfAttribute(Foo.class), foo));
```

Hope that helps!?
Niall

**Comment by bluedoo** [comment]
I tried updating my `ResultSet` to use the above `ResultSet<Foo> resultSet = foos.retrieve(equal(selfAttribute(Foo.class), foo));` but I'm still getting the same issue.

Are you able to produce a working example of what I've given under `Steps to Reproduce` by any chance?

It just seems that it always returns equal objects, regardless of your call, your hashCode or your equals method?

**Comment by npgall** [comment]
In step 6 of your steps to reproduce the problem, isn't it correct that two objects should be stored in the collection and returned?

"test" and "TEST" will not be equal according to String.equals()

**Comment by bluedoo** [comment]
Ah yes, good point. Should be `equalsIgnoreCase`
