### ISSUE TITLE
How to delete an off-heap IndexedCollection?

### ISSUE THREAD

**Issue by Cueroqu** [npgall/cqengine#104]
My program creates IndexedCollection using constructor like this:

`
currentCollection = new ConcurrentIndexedCollection<>(
                OffHeapPersistence.onPrimaryKey(/* SOME ATTRIBUTE */));
`
`
currentCollection.add(/* add data item one by one*/);
`

If I don't want the collection any more, how can I delete it? Is just doing below enough?

`
currentCollection.clear();
currentCollection = null;
`

or should I do something more?
Thanks.

**Comment by npgall** [comment]
There is no need to call clear() actually.

The off-heap memory will be freed as soon as the Persistence object/IndexedCollection is garbage collected. The Persistence object has a finalizer method, which the GC will invoke, and the finalizer method will then free the off-heap memory.

However if you really want to free it sooner before the GC occurs, you can call close() on the Persistence object directly.

```java
OffHeapPersistence<Foo, PkType> persistence = OffHeapPersistence.onPrimaryKey(/* SOME ATTRIBUTE */);
IndexedCollection<Foo> currentCollection = new ConcurrentIndexedCollection<>(persistence);

...
persistence.close();
currentCollection = null;
```
HTH!
Niall

**Comment by Cueroqu** [comment]
Gotcha, thank you!

**Comment by archenroot** [comment]
@npgall - I use cqengine now not only as master more centralized engine, but also as local thread more like cache store. What is the fastest way to clean it and load new data from batch?

I think recreating whole object via null, new collection and setting again all indexes is the most expensive.

I think clear() will fit in my case best.

**Comment by npgall** [comment]
I'm not sure really, you might have to try it! 

If you call clear(), and then reuse an existing collection, then it could be a bit more efficient than creating a new collection because the off-heap memory for the collection will already be allocated. But on the other hand, calling clear() will require existing indexes to be modified, which would not be required if you simply created new indexes in a new collection. So it might depend on the number of indexes you have or maybe on the speed of memory access on the particular hardware.

**Comment by muhdkhokhar** [comment]
Hi 
My application need regular refreshes. I am planning to close the persistence and init agian would that be fine
