### ISSUE TITLE
Collection & Index Persistence

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#108]
Could we possibly get some documentation on the different types of persistence?

1. It's unclear what the differences of on-heap and off-heap are
2. It's also unclear where data is stored with Disk storage and how you can specify your own paths
3. It would also be nice to know what files get stored with Disk collection/index storage and what each file contains and its purpose
4. It would be good to get some information on concurrent file access for Disk storage, i.e. Storage over NAS with multiple nodes accessing it simultaneously
5. It would be nice to know what the performance differences are with all the different storage options

**Comment by npgall** [comment]
Isn't a lot of this covered in the documentation and JavaDocs already? For example there's an example titled how to _"store the collection in a particular file on disk"_ on the front page [here](https://github.com/npgall/cqengine#persistence-on-heap-off-heap-disk). You can also find more detail in the JavaDocs for each of the [Persistence](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/persistence/Persistence.html) implementations. But anyway, to answer in a bit more detail..

**Persistence files**
When DiskPersistence is configured, there will be one file per IndexedCollection and it will contain the collection itself and all of the disk indexes added to it. As mentioned in [DiskPersistence](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/persistence/disk/DiskPersistence.html), it _"supports fully concurrent reads and writes by default. This is because it enables Write-Ahead Logging ("WAL") journal mode in the underlying SQLite database file."_

Basically, the disk persistence is represented as a SQLite database file on disk, and the off-heap persistence is represented as an in-memory SQLite database.

**Concurrency**
The disk persistence supports fully concurrent reads and writes. OTOH the off-heap persistence supports concurrent reads, but not concurrent writes, where writes will block reads.

But.. this applies to concurrency within the same application (i.e. multi-threaded access). It does not apply to multiple processes or multiple machines accessing the same SQLite disk persistence file at the same time though.

**Multiple nodes support & caveats**
If you want to share the persistence file between multiple processes (application/instances) or machines, you can follow the standard guidance for SQLite.

Generally, it's not recommended to use SQLite (and therefore CQEngine's disk persistence) on multiple nodes sharing the same file, as an alternative to a centralized database, if there will be writes from multiple applications or machines into the same database at the same time. It is possible to share access between machines, but you have to do 2 things:
* (1) Disable the WAL mode in SQLite, and use the regular rollback journaling mode instead. This means you will lose support for concurrent writes. So while it will support concurrent reads, writes will block reads. Read about the differences between SQLite's regular [rollback journal](https://www.sqlite.org/lockingv3.html#rollback), and its [WAL journaling mode](https://www.sqlite.org/wal.html).
* (2) If you will store the file on a NAS and there will be multiple machines accessing it concurrently, you will need to ensure that your NAS or shared file system **supports file locking** properly. Some shared file systems support file locking, some do not. See this [SO post](http://serverfault.com/questions/62609/can-sqlite-be-used-with-glusterfs) for more information.

You can change SQLite config such as the journaling mode by creating the DiskPersistence via [DiskPersistence.onPrimaryKeyInFileWithProperties\()](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/persistence/disk/DiskPersistence.html#onPrimaryKeyInFileWithProperties-com.googlecode.cqengine.attribute.SimpleAttribute-java.io.File-java.util.Properties-). For example, take a look at how CQEngine itself does it [here](https://github.com/npgall/cqengine/blob/2.9.0/code/src/main/java/com/googlecode/cqengine/persistence/disk/DiskPersistence.java#L65). The properties you can set correspond to [pragma statements](https://www.sqlite.org/pragma.html) supported by SQLite.

In general, I would not recommend to share the disk persistence file between processes/applications/machines (and so WAL mode has to be disabled) unless the write volume will be quite low and you can tolerate brief pauses in reading threads while writes are performed.

A better approach is usually to have a separate copy (or a shard) of the collection on each application-tier machine, which mirrors some central database.

**On-heap versus off-heap index performance**
On-heap indexes use standard on-heap Java data structures (e.g. Maps from the JDK, and some custom ones). These usually outperform off-heap and disk indexes, because the killer feature of on-heap data structures/indexes is they can store a reference to the indexed object directly, which means retrieval be very fast. But for extremely large collections, GC overhead can become a problem. So sometimes there can be a threshold depending on the application, where on-heap performance may degrade and off-heap may be preferable.

The off-heap indexes use SQLite as an efficient front-end for a b-tree index in RAM or on disk. As these indexes can't store a Java object reference, they need to store the value of a primary key of each object instead. Which means on retrieval, it can require more indirection which results in slower retrieval performance than the on-heap indexes. 

There are so many variables, your best bet is to test these various options with your application's dataset. I'm not sure if you want more detail than this(!) so hope that helps for now!

Niall
