### ISSUE TITLE
2.9.1 handicapped subclassing Equal

### ISSUE THREAD

**Issue by yrashk** [npgall/cqengine#109]
When I upgrading to 2.9.1 (2.9.0 went through fine), I experienced a new test failure.

I am using a subclassed implementation of Equal to provide special handling of certain cases of equality (particularly, making sure `byte[]` equality comparison is done right [as opposed to the solution suggested in #75, requiring wrapping byte arrays]). It worked fine until I attempted to update cqengine to 2.9.1.

I am not sure why this behaviour happened now (perhaps some of the optimizations affected the internal workflow — yet to figure out the exact reason), but I was thinking if it would make sense to replace `queryClass.equals(Equal.class)` and similar constructs to `Equal.class.isAssignableFrom(queryClass)`? Any objections to this?

**Comment by yrashk** [comment]
(maybe @uujava will be able to provide an insight as to why subclassing Equal broke in 2.9.1? — though it might be not as important as fixing the issue itself)

**Comment by npgall** [comment]
Hi Yurii, I'm not sure how that worked before then! I don't think we made major changes in this area in 2.9.1 except for a few performance tweaks.

Are you sure this issue was introduced in CQEngine 2.9.1?

I can see how it could be useful to have subclasses of Query objects. But AFAICS the current behaviour has been there for a long time. Could you provide a test case or investigate further on your side?

If necessary I'm open to changing how we determine query type as you suggest. Using `instanceof` could be an option too. However the [AbstractAttributeIndex](https://github.com/npgall/cqengine/blob/2.9.1/code/src/main/java/com/googlecode/cqengine/index/support/AbstractAttributeIndex.java#L68) which is a superclass of several indexes, depends on class equality using class.equals() as well, and we should be consistent in the approach.

**Comment by yrashk** [comment]
To be honest, I'm also quite puzzled now as to how it worked before. And
yet, I just reran the same test on 2.8.0, 2.9.0 and 2.9.1 and only .1
actually failed.

The test that's failing is in the cross referenced issue in es4j.

I'm happy to help changing the convention to instanceof. Any further
thoughts on this?

**Comment by npgall** [comment]
I don't think it would be enough to use `instanceof` alone - we need to find a solution for `AbstractAttributeIndex` as well. Any ideas?

Can you get the complete stack trace for the failure?

**Comment by yrashk** [comment]
I am not at my computer right now but the actual stacktrace is basically
falling through the type checks in UniqueIndex#retrieve (because of
subclassing) and then causing the exception.

**Comment by npgall** [comment]
Ah. In that case it's probably [this addition](https://github.com/npgall/cqengine/blob/2.9.1/code/src/main/java/com/googlecode/cqengine/index/unique/UniqueIndex.java#L115) to UniqueIndex, which actually introduced `instanceof` instead of using class.equals(). I've patched the issue which will reintroduce the previous behaviour (while retaining the performance improvements of 2.9.1).

I think this might mean, if you have been using a subclass of Equal query before now, that the indexes would have reported that they didn't support that query subclass. So CQEngine would have refused to use indexes to evaluate that query.

**Comment by yrashk** [comment]
So, do we need to take any further action to properly enable subclassing
Equal and other queries?

I will test the fix tonight or tomorrow (thanks!)

**Comment by npgall** [comment]
I'll release 2.9.2 now with the patch. It should fix the exception for you. 

Basically 2.9.1 introduced a subtle issue where `UniqueIndex.supportsQuery()` reported true for query subclasses, whereas previously it reported false. This issues isn't picked up in CQEngine tests because queries typically are not subclassed. However it caused problems for you in ES4J due to query subclasses there. The current implementation of UniqueIndex (and most indexes) isn't actually compatible with query subclasses, hence the problem.

So.. although 2.9.2 should work fine with ES4J again, just bear in mind that ES4J is possibly not getting the best performance from CQEngine's built-in set of indexes if it's subclassing the queries. If you need this changed, I'm open to it, but it's not just a case of using `instanceof` - the solution needs to account for how query classes are currently stored in maps too.

However if you are using custom indexes in ES4J, or subclassing the CQEngine indexes, then this should not be an issue as it's entirely up to each index (or index subclass!) to decide how or if it will accelerate query subclasses.

**Comment by yrashk** [comment]
Just checked, 2.9.2 works fine. Thanks a lot!

Most of indices are not the stock CQEngine indices (memory or sqlite). Memory is used for testing or for cases when extreme performance is required. The rest usually goes on disk (pgsql or mvstore).

I want to understand better what you mean by "the solution needs to account for how query classes are currently stored in maps too" — can you give some pointers? I want to see if I can contribute the `instanceof` change in the way you see it should happen.

**Comment by npgall** [comment]
Sorry I meant to say a Set, not a Map!

I created a new issue #111 to discuss improving support for query subclasses using `instanceof`. Let's continue discussion there.
