### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by gavrmike** [npgall/cqengine#120]
Hi!

I would like to use cqengine in my project.
I have a few questions about this database:
1. is it correct way to use for bulk read opeartions: smth like this select * from a where (a.primary_key % 10 = 1)
2. Does exists comparison between cqengine and postgresql or another?
3. Does database has compression data?
4. Is "group by" by non-unique indexed key is good decision? How it works?

**Comment by npgall** [comment]
Hi,

CQEngine isn't exactly like a database.

Regarding your questions:

1. You can bulk read the entire collection in CQEngine just by iterating it.

However - if your actual goal is to read only 10% of items in the collection, then FYI a query like that "where (a.primary_key % 10 = 1)" would not be very efficient in CQEngine or in conventional databases either for that matter. It's because it requires every primary key to be read in order to determine if it matches the query.

A better approach would be to add a separate 'partition' integer attribute (and column in the database) to each row/object, and then to assign each row to one of 100 partitions. This way you can add an index on 'partition', which will allow you to retrieve any % of the rows efficiently without having to scan the entire table. For example to retrieve 1% of rows, use a query to select one (potentially random) partition: "select ... where (a.partition = 5)". To retrieve 10% of rows: "select ... where (a.partition between 1 and 10)". This is a more efficient way to bulk read 10% of the data.

2. Not really, there is no comparison with postgres. Just read the documentation for CQEngine you will find it's not much like postgres or any conventional database! CQEngine is not designed to replace conventional databases at all. Typically it is used alongside them.

3. No CQEngine does not compress the data per-se.

4. CQEngine doesn't support GROUP BY directly at all. Read the documentation: https://github.com/npgall/cqengine#grouping-and-aggregation-group-by-sum . The current recommendation is to use Java 8 streams to group CQEngine results. 

Hope that helps!
Best regards,
Niall

**Comment by gavrmike** [comment]
Thanks a lot, for answer!
