### ISSUE TITLE
benchmark for delection/insert/update?

### ISSUE THREAD

**Issue by publicocean0** [npgall/cqengine#121]
i can t find benchmark for crud operations

**Comment by npgall** [comment]
The location of the benchmark is well documented on the front page!?!

It points to [documentation/Benchmark.md](https://github.com/npgall/cqengine/blob/master/documentation/Benchmark.md) which includes full details and a link to the benchmark source code.

The existing benchmark covers SELECT and INSERT operations, but it does not cover DELETE and UPDATE operations. If you would like to enhance the benchmark to measure the performance of those additional operations, FYI this project is open to pull requests :)

**Comment by publicocean0** [comment]
Ok. I tested library using my laptop. Using RAM perfomance is very good. 
The problem is using DISK. 
Inserting 10 cars 20 ms -> 2ms per car
inserting 100 cars 17000 -> 170 ms per car 


the insertion is not proportional on disk. It seams like n^2

**Comment by npgall** [comment]
CQEngine does implement those optimizations. There is support to insert a large number of objects in a single round trip to disk instead of one round trip per object. However currently, I guess you are incurring one round trip per object which would explain that latency.

Which method are you using to add objects to the collection - `add()`?

If so, you can use the `addAll()` method to insert the objects in batches instead. It should speed up the insertions considerably.

For advanced performance tuning, there is some documentation about doing bulk imports as well, in the JavaDocs for [IndexedCollection.update()](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/IndexedCollection.html#update-java.lang.Iterable-java.lang.Iterable-com.googlecode.cqengine.query.option.QueryOptions-).

As those JavaDocs mention, furthermore, if you want to populate the IndexedCollection from scratch as quickly as possible, for example at startup, you can also optionally set a [BULK_IMPORT](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/index/sqlite/support/SQLiteIndexFlags.html#BULK_IMPORT) flag in the query options.

Let me know how this goes. There's actually a few other bulk import options too which I haven't mentioned yet, because they are not typically needed.

**Comment by publicocean0** [comment]
I will try but i m worried about ...

inserting 100 cars 17000 -> 170 ms per car 

17 seconds for inserting just 100 cars.

**Comment by npgall** [comment]
Can you share a test case which demonstrates that problem? I'd be interested to see which indexes are configured. The more indexes, the higher the write IO will be. 

Also I'd like to examine the distribution of values amongst the buckets in the indexes. I wonder if you're seeing some kind of problematic pattern in the data which is causing a problem. I've previously measured thousands of inserts per second using batching. But 170ms per insert sounds high, regardless of whether it's a batch insert or not.

**Comment by publicocean0** [comment]
Yes surely :) 

`	DiskPersistence<Car, Integer>  p= DiskPersistence.onPrimaryKeyInFile(Car.CAR_ID, new File("cars.dat"));
		// We will store the cars in TransactionalIndexedCollection, which provides MVCC support...
		IndexedCollection<Car> cars = new TransactionalIndexedCollection<Car>(Car.class,p
			);

		// ===== Examples of modifying the collection using MVCC transactions... =====

	
		long t=System.currentTimeMillis();
		for(int i=1;i<1000;i++) cars.add(CarFactory.createCar(i));
		System.out.println(System.currentTimeMillis()-t);


	`
