### ISSUE TITLE
best practice for instantiating collections

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#127]
Is it okay to do something like this or will there be a hit of some sort to the performance or functionality?

```
 public Boolean insert(final Foo foo) {
        IndexedCollection<Foo> foos = new ConcurrentIndexedCollection<Foo>(DiskPersistence.onPrimaryKey(Foo.ID_INDEX));
        return foos.add(foo);
    }
```

The alternative would be to either make `foos` a `public static` or create a factory of some sort to retrieve the instance.

Which approach is recommended?

**Comment by bluedoo** [comment]
UPDATE: When I run this `insert` method, I keep getting: 

> java.lang.IllegalStateException: Failed to open SQLite connection for file: /Users/bluedoo/project/cqengineproject

Am I doing something wrong here?

**Comment by bluedoo** [comment]
UPDATE: The above error seems to be related to SQLite dependency (which a pure java version of cqengine would've avoided)

> Caused by: java.lang.Exception: No native library is found for os.name=Mac and os.arch=x86_64

**Comment by npgall** [comment]
To answer your first question: I would recommend to NOT do that :) It will be better to cache the IndexedCollection object in memory, between requests. 

Although it might not make a huge difference right now, I have previously measured a 1-2ms latency to access the persistence file afresh in some cases. So in future I might update the Persistence object (encapsulated in the IndexedCollection) to cache connections. So if you follow this recommended approach now, you might benefit from further performance improvements in future.

Regarding the other questions. Youoften omit the cause exception when you report problems! I have no idea what's going wrong because you omitted the important details there.

Regarding a pure java version: pure Java does not support off-heap memory :) So it would not be possible to support all of the current features of CQEngine if it was limited to pure Java.

However you can omit the SQLite jar from your list of dependencies if you wish, and just avoid using Disk or OffHeap persistence. CQEngine only has a soft dependency on SQLite intentionally for this reason. The native code is not essential, and you can exclude it if you don't need the features it provides.

Hope that helps!

**Comment by bluedoo** [comment]
@npgall thanks for this feedback, it's very helpful. The only thing I'm still confused about is whether it's possible or not to have Disk persistence without SQLite? In theory one could implement this with pure Java, correct?

**Comment by npgall** [comment]
That's correct. DiskPersistence could be implemented with a pure-Java library. However the advantage of SQLite is that it supports both off-heap memory and disk persistence in a single implementation, so it was easier to use.
