### ISSUE TITLE
collection to json

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#134]
I'm not sure if gson or jackson is a good candidate for converting an IndexedCollection to json or xml. Is there a native way to cqengine? If not, what's the recommended approach? converting IndexedCollection to a List each time would probably be wasteful right?

**Comment by npgall** [comment]
There's no native way. But as IndexedCollection is a java.util.Collection, you can use any library which works with standard collections to convert objects in an IndexedCollection to/from json or xml.

That said, things to look out for:

Look for a json/xml serializer which supports streaming. That is- 

- When serializing the objects in the collection, it would be ideal (I guess) if the library could write the json/xml for each object to an OutputStream on-the-fly instead of buffering the json/xml for all objects in memory at once.

- When deserializing objects, it would be ideal if (1) the library could give you each object one at a time, so you can add them directly to an IndexedCollection on-the-fly. Or, (2) if you could give it a collection (i.e. the IndexedCollection) into which it would add the objects. This is to avoid copying the objects into an intermediate collection first (such as a List), where you would then need to add all objects in that collection into an IndexedCollection afterwards. Alternatively you could (3) use CQEngine's WrappingPersistence to wrap a List, but this option is not ideal. Options (1) or (2) would be best.

Hope that helps!

**Comment by bluedoo** [comment]
@npgall so would you recommend gson or jackson?

**Comment by npgall** [comment]
I don't have any particular recommendation. I have used jackson more personally, but YMMV!
