### ISSUE TITLE
ResultSets can provide more information in custom spliterator

### ISSUE THREAD

**Issue by shollander** [npgall/cqengine#142]
Since ResultSet reports a size, it would be nice if the spliterator that it returned would report a size as well (through the _estimateSize()_ method.

I also noticed that for some reason the spliterator of ResultSet does not split well. Perhaps that can also be improved.

**Comment by npgall** [comment]
Hi shollander,

> Since ResultSet reports a size, it would be nice if the spliterator that it returned would report a size as well (through the estimateSize() method.

This is a good suggestion, thanks!

Currently CQEngine itself remains compatible with Java 6-7, and the integration with Java 8 streams is actually handled by a sister library [cqengine-stream-support](https://github.com/npgall/cqengine-stream-support/blob/master/code/src/main/java/com/googlecode/cqengine/stream/StreamFactory.java). However it should be possible to add this feature to the sister library, so I'll keep this issue open as a request for this enhancement. Thanks!

> I also noticed that for some reason the spliterator of ResultSet does not split well. Perhaps that can also be improved.

Can you elaborate on what you mean by it does not split well? FYI the spliterator obtained from the ResultSet cannot be used with parallel streams. You can use the `StreamFactory` class to obtain a non-parallel Stream for use with Java 8, as discussed in [Streams.md](https://github.com/npgall/cqengine/blob/master/documentation/Streams.md).

**Comment by shollander** [comment]
@npgall, When calling `trySplit()` on the spliterator of a `ResultSet`, the original spliterator is left with zero elements, and the new spliterator has all the elements of the original. For example, suppose ResultSet r1 has 4 elements.
```
ResultSet<MyObject> r1 = collection.retrieve(query);
Spliterator<MyObject> split1 = r1.spliterator();
Spliterator<MyObject> split2 = split1.trySplit();
```
Idealy, the number of items in `r1` should be (somewhat) evenly distributed between `split1` and `split2`. What happens though is that `split2` will now contain all the items and `split1` will be empty.

**Comment by npgall** [comment]
Thanks for the update shollander. 

That `rs.spliterator().trySplit()` behavior is inherited from `java.util.Iterable` (which `ResultSet` extends) as provided by Java 8 when CQEngine is running on Java 8. So I can't improve the `trySplit()` behavior until CQEngine drops compatibility with Java 6-7.

However I'm not sure if `trySplit()` will ever be much useful with CQEngine ResultSets anyway, because remember that in CQEngine ResultSets don't actually contain any results, because of lazy evaluation. The ResultSet is just a _thing_ which the application can iterate, which drives CQEngine to compute each next result in turn on-the-fly while the application iterates.

I'll have a think about estimateSize() and this trySplit() behavior though. I plan to finally drop compatibility with Java 6-7 soon, so that integration with Java 8 streams can be improved.

**Comment by npgall** [comment]
This is now done, in release 3.x :)
