### ISSUE TITLE
Switch from kryo to kryo-shaded to hide asm which can prevent classloading issues

### ISSUE THREAD

**Issue by bseiller** [npgall/cqengine#146]
We are using Glassfish as application server which brings its own rather old version of asm as an OSGI module.
cqengine has a transitive dependency to asm 5.0.3 via kryo.
This caused some classloading issues, which we resolved by changing our dependency graph.
kyro-shaded would have made the integration of cqengine easier - as we learned later when we used kryo directly for another taks.

This seems also to be an issue for others as it is mentioned here
https://github.com/EsotericSoftware/kryo#integration-with-maven

**Comment by npgall** [comment]
I'm a bit hesitant to do this, because if CQEngine used the shaded version of Kryo by default, then it would make applications which use CQEngine more bloated. Instead, I'd prefer if end users had the choice to use shaded libraries only when needed.

In your application, would it be possible for you to exclude 'kryo', and add a dependency on 'kryo-shaded' there instead?

**Comment by bseiller** [comment]
I see your point - but I'm wondering: How much bloat would there really be? 
Since the shaded version is just an all-dependencies-included version of the standard version only projects that already contained at least one of those dependencies (asm, minlog, objenesis) would get bloated. At the same time they would get the possibility to change their own version of those dependencies without interfering with the dependencies of CQEngine ->kryo.
Just a thought ;)

We should be able to replace the kryo dependency of CQEngine with kryo-shaded, as long as we keep it to the same version of the kryo-shaded which we depend on already in another module.
Since we are building an ear all non-ejb jars are being accumulated in one lib directory at the end, so different versions of the same dependency won't work.
I'll give it a try and report back.

**Comment by npgall** [comment]
Well if we take it to the extreme where every library shaded its dependencies (e.g. recursive shading), then there would be an enormous amount of bloat :)

There is actually a shaded version of CQEngine as well, which shades Kryo and Kryo's dependencies asm, minlog, objecensis too if that helps. However unfortunately there's an issue with how it's currently packaged (issue #144) which will be fixed in the next release.

**Comment by bseiller** [comment]
Ok, excluding 'kryo' and using 'kryo-shaded' instead works fine for us as far as I can see.

I'll monitor #144 and #86 to get notified concerning -all.jar 

Thanks for the help and the constructive discussion!
