### ISSUE TITLE
Replace persistence through SQLite with H2 or similar JVM only DB?

### ISSUE THREAD

**Issue by wilx** [npgall/cqengine#156]
AFAIK, CQEngine uses SQLite for off-heap storage of collections. This is sub-optimal as the use of SQLite requires use of pre-compiled binaries. Is there a way to replace the persistence layer with something like H2 database or similar JVM only database?

**Comment by npgall** [comment]
Hi Václav,

Yes it is totally possible to use an alternative persistence layer.

Basically if you can implement a persistent java.util.Set (to persist the
collection itself) and a persistent java.util.NavigableMap (as a general
purpose index), then they can be used as the basis for a new type of
Persistence with CQEngine quite easily.

Im not sure if it's still using CQEngine right now, but I know the ES4J had
implemented a Postgres persistence layer for CQEngine so you could take a
loot at that: https://github.com/eventsourcing/es4j

So for background you might ask why does CQEngine use SQLite? Well your
definition of sub-optimal is subjective :) SQLite supports persistence to
disk and to off-heap memory, while H2 does not support the latter. The use
of SQLite therefore means CQEngine can offer off-heap persistence which is
a key out of the box feature. It also supports a wider variety of indexes
such as FTS and R-tree. CQEngine doesn't use those indexes currently but I
thought they might be useful for use in the future.

When researching the options, I found that SQLite is much more very widely
used than perhaps a lot of Java developers know. It is preinstalled on all
operating systems, and so has a much larger installed base than H2 or
perhaps any other database:
https://db-engines.com/en/ranking_trend/system/H2;SQLite

However indeed the downside is SQLite requires a precompiled binary per
platform. If this is a problem you can actually delete the binaries from
the SQLite jar for the platforms you don't use though.

I was originally concerned that the use of precompiled binaries might
compromise
Java's write once run anywhere portability too. But I changed my mind on
this having seen the number of platforms supported by SQLite. SQLite is
available on all of the platforms supported by Java, and it's typically
ported to new platforms sooner than Java is.

Anyway that's the background story :) I'm happy to help you as much as I
can if you do go ahead with an alternative persistence.

Best regards,
Niall


On 21 Aug 2017 07:29, "Václav Haisman" <notifications@github.com> wrote:

AFAIK, CQEngine uses SQLite for off-heap storage of collections. This is
sub-optimal as the use of SQLite requires use of pre-compiled binaries. Is
there a way to replace the persistence layer with something like H2
database or similar JVM only database?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/npgall/cqengine/issues/156>, or mute the thread

**Comment by npgall** [comment]
Closing this for now. Feel free to reopen if you need more info.
