### ISSUE TITLE
garbage control for iterator creation to reduce GC impact, and provide initial size of collection size

### ISSUE THREAD

**Issue by loveyoupeng** [npgall/cqengine#162]
only a suggestion, could you consider replace all iterator operation with for-index based looping or implement cached/pooled/reuseable iterators to reduce garbage generation to reduce GC impact to minimal. 
and provide api to let user give hint on the collection size during initialization to reduce runtime resizing of collection.

**Comment by npgall** [comment]
**Configuring initial size**
There actually is an API which allows you to configure the initial size of the collection to reduce resizing. It's in the Persistence object, which you can optionally supply to the constructor of the IndexedCollection.

It works as follows:
* If you don't supply a Persistence object when creating the IndexedCollection, it will use OnHeapPersistence by default, with default settings.
* However if you want to override the default settings, you can supply an OnHeapPersistence object explicitly, configured with those settings which you can supply to [this constructor](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/persistence/onheap/OnHeapPersistence.html#OnHeapPersistence-com.googlecode.cqengine.attribute.SimpleAttribute-int-float-int-).

**Regarding iterators**
Regarding your other question about iterators: it's not quite as straightforward as replacing iterators with indexed-based looping. 

Evaluating a query often involves lookup operations which are not sequential. Typically a query will read from several data structures (the collection itself and also from several indexes). Iterators are used to maintain pointers to the locations in each data structure which the engine is reading. The number of iterators created is usually proportional to the number of non-sequential reads required by the query. The number of non-sequential reads required, in turn, often relates to the degree to which the data required by the query is _fragmented_ in indexes.

**Typical bottlenecks**
There is no shortage of bottlenecks which can affect query performance(!), but I usually find the bottlenecks relate to algorithmic issues - such as excessive sorting, excessive filtering, or suboptimal indexes. I don't usually find that the number of iterators created is a problem itself. Is it possible that it's a symptom, rather than the root cause? Addressing these bottlenecks usually involves reconfiguring indexes to reduce fragmentation, looking at [OrderingStrategies](https://github.com/npgall/cqengine/blob/master/documentation/OrderingStrategies.md), [MergeStrategies](https://github.com/npgall/cqengine/blob/master/documentation/MergeStrategies.md), or rethinking how queries are structured.

**Tuning fragmentation**
The first thing that comes to mind, is to look at [IndexQuantization](https://github.com/npgall/cqengine/blob/master/documentation/IndexQuantization.md) as a way to tune the fragmentation within indexes. However note that fragmentation is neither bad nor good. The optimal degree of fragmentation actually boils down to a tradeoff between providing fast random access for fine-grained queries, and providing fast sequential access for coarse-grained queries. Basically:

* If your queries will be very specific (think: 'equal' queries), then it makes sense to configure indexes to have a large number of buckets (to be _intentionally fragmented_), such that each bucket will contain exactly the data sought by the query. 
* But if your queries will be vague (think: range or 'between' queries), then it can be harmful to configure indexes with a large number of buckets, because it makes the data which must be accessed by the query more fragmented.

Perhaps if you see an excessive number of iterators created, then it's a symptom of your index being too fragmented.

Apart from that, it's totally possible that you are encountering some bottleneck which I have not seen before. If you can't get to the bottom of the iterators issue, could you share a test case which I can run to reproduce and investigate the problem?

**Comment by npgall** [comment]
Ok. I will resolve this for now. Feel free to reopen, or create another issue if you still have problems!
