### ISSUE TITLE
Index and Updating Objects

### ISSUE THREAD

**Issue by H-K-47** [npgall/cqengine#164]
See last response

**Comment by H-K-47** [comment]
After digging into the code, this happens because the current value of an object indexed attribute is used to lookup indexes - which makes no sense to me.

In AbstractMapBasedAttributeIndex the removeAll is done like this

```
 @Override
    public boolean removeAll(ObjectSet<O> objectSet, QueryOptions queryOptions) {
        try {
            boolean modified = false;
            ConcurrentMap<A, StoredResultSet<O>> indexMap = this.indexMap;
            for (O object : objectSet) {
                Iterable<A> attributeValues = getAttribute().getValues(object, queryOptions);
                for (A attributeValue : attributeValues) {

                    // Replace attributeValue with quantized value if applicable...
                    attributeValue = getQuantizedValue(attributeValue);

                    StoredResultSet<O> valueSet = indexMap.get(attributeValue);
                    if (valueSet == null) {
                        continue;
                    }
                    modified |= valueSet.remove(object);
                    if (valueSet.isEmpty()) {
                        indexMap.remove(attributeValue);
                    }
                }
            }
            return modified;
        }
        finally {
            objectSet.close();
        }
    }
```

The lookup    StoredResultSet<O> valueSet = indexMap.get(attributeValue); is unneeded - the object should be simply removed from ALL available valueSets - why add this overhead ?

**Comment by H-K-47** [comment]
I am suggesting the following change to the AbstractMapBasedAttributeIndex - i had to extend the class as a workaround for now

```
// can not overload with same parameterized var
    public boolean removeAll(ObjectSet objectSetNoParam, QueryOptions queryOptions) {

        ObjectSet<O> objectSet = objectSetNoParam;

        try {

            boolean modified = false;
            ConcurrentMap<A, StoredResultSet<O>> indexMap = this.indexMap;

            Set<Map.Entry<A, StoredResultSet<O>>> entrySet = indexMap.entrySet();

            Iterator<Map.Entry<A, StoredResultSet<O>>> it = entrySet.iterator();

            for (O object : objectSet) {

                // remove from index
                while (it.hasNext()) {
                    Map.Entry<A, StoredResultSet<O>> entry = it.next();

                    A attributeValue = entry.getKey();
                    StoredResultSet<O> valueSet = entry.getValue();
                    modified |= valueSet.remove(object);

                    if(valueSet.isEmpty()) {
                        indexMap.remove(attributeValue);
                    }
                }
            }



            return modified;
        }
        finally {
            objectSet.close();
        }
}
```

Basically simply iterate through all valuesets and remove the object regardless of the index, and if the valueset is empty - then remove the index itself

**Comment by npgall** [comment]
This is the expected behaviour actually.

There is no magic where CQEngine monitors the fields in your objects. The code above unfortunately would not scale either as the time complexity to remove an object would be O(n * num_indexes).

You can find a discussion about this in the forum:
https://groups.google.com/d/msg/cqengine-discuss/EQRjtCMxQv8/xhV2LZWn6gkJ

However to summarize what you need to do: take a look at the support in [TransactionalIndexedCollection](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/TransactionalIndexedCollection.html#update-java.lang.Iterable-java.lang.Iterable-) for atomically replacing one version of an object with another using the [update()](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/TransactionalIndexedCollection.html#update-java.lang.Iterable-java.lang.Iterable-) method.

You don't technically need to use the `TransactionalIndexedCollection`. You can alternatively use the 'update()' method in the `ConcurrentIndexedCollection` as well, if you can tolerate the change not being atomic.

**Comment by H-K-47** [comment]
Yeah the post you linked is actually from me - im updating from the 1.x version to 2.x right now. The TransactionalIndexedCollection isn't working for me because of some dead locks which might be related to searches (btw your samples never account for closing the search when using uniqueResult)

>>In general a rule of thumb is: don't modify any fields which are indexed,

Again you make it look like i have power over this - the usecase still stands - i don't know which fields are modified outside - i only catch the update/save method for the whole object. And i really do believe that what you are saying about "expected behaviour" is dead wrong. I posted a sample about producing a very serious bug in your library - you can't talk that away with being "by design".

O(n * num_indexes). only applies to updates / deletions and these happen far less than read/search of objects. There is something wrong when you engine believes it deleted an object but keeps indexes of phantom objects.

**Comment by npgall** [comment]
By "expected behavior" I just mean that the behavior that you see, is the behavior I would expect when fields are modified. I'm not saying it's perfect, but I actually don't think there is a perfect solution to this, because every choice we have has tradeoffs.

For what it's worth, this behavior is consistent with the specifications of the JDK Set and Map interfaces.  For example the [JavaDoc for the java.util.Set](https://docs.oracle.com/javase/8/docs/api/java/util/Set.html) interface states _"Great care must be exercised if mutable objects are used as set elements"_. Remember that CQEngine's IndexedCollection [is an implementation](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/ConcurrentIndexedCollection.html) of a Set. 

The unit tests in the project also use [guava-testlib](https://github.com/google/guava/blob/master/guava-testlib/src/com/google/common/collect/testing/SetTestSuiteBuilder.java) to verify programmatically that the IndexedCollection [is compliant](https://github.com/npgall/cqengine/blob/2.12.2/code/src/test/java/com/googlecode/cqengine/ConcurrentIndexedCollectionTest.java) with the specification of a Set.

Consider the following class:
```java
public class PhantomObjectInJDKHashMap {

    static class Person {
        String name;
        int age;

        @Override
        public int hashCode() {
            return 31 * name.hashCode() + age;
        }

        @Override
        public String toString() { return "Person{name='" + name + "', age=" + age + "}"; }
    }

    public static void main(String[] args) {
        Map<Person, Boolean> map = new HashMap<>();

        Person person = new Person();
        person.name = "joe";
        person.age = 5;

        map.put(person, true); // add Person to HashMap

        person.age = 6; // Change Person's age
        map.remove(person); // remove Person from HashMap

        System.out.println(map); // Person is still in the HashMap
    }
}
```

..basically the exact same problem happens in the JDK Collections framework. If you search for "mutable object in set" or "mutable object in hashmap" you will find lots of discussions about it.

This is a difficult problem in general (for CQEngine and other collections including the JDK), because in order to keep the collection in sync with changes made to fields, the collection needs to be notified of *both the old and the new* value for the field, each time the field is modified. This is so it can remove the old entry from an index (or from a bucket in the case of a HashMap), and then add a new entry.

In the forum I had suggested a few options:
1. [don't give untrusted code your actual mutable object - give it a proxy instead](https://groups.google.com/d/msg/cqengine-discuss/EQRjtCMxQv8/SzKBIjmxV5MJ). The proxy can record invocations on setter methods and simply record them in a list of modifications to be applied later. Then when you get the object back, you can safely apply all modifications all at once. Note: you could look at [ByteBuddy](http://bytebuddy.net/#/) or similar, to generate Proxy objects for POJOs dynamically.
2. perhaps simpler than a proxy: for each .. field in your object (which might be modified by untrusted code), [add a second counterpart field](https://groups.google.com/d/msg/cqengine-discuss/EQRjtCMxQv8/oMX_VxupJ70J) of the same type which you designate as mutable. The public setters and getters operate on the mutable variants. CQEngine can index the original supposedly immutable fields. When you get the object back from untrusted code, if any mutable variants have changed, remove the object from the collection, copy mutable values into the 'immutable' fields, re-add the object.

Are these options feasible in your application? The idea is to just modify the setter methods in the objects you give to the "untrusted" code, so that you will have a record later of how the fields were changed.

**Comment by H-K-47** [comment]
@npgall Please think about adding a solution for the given problem when you consider the objects all have a uniqueID.

Meanwhile, my workaround is now that i keep a copy of each object in a hashmap referenced by its primary ID, i only expose the objects i have in the cqengine index now to external calls. When a save() is called i simply lookup the original object by its ID and tell cqengine to remove this object (since it retains the original field values) and add the new modified one. The modified object will then also be updated in my hashmap

**Comment by npgall** [comment]
The only way to delete an object from the indexes efficiently, is when we know the _old_ value of each field which was modified.

Even if there was a unique id, it would still not be possible to delete from all indexes an object whose field(s) had been modified, without doing a brute force scan through all of the indexes, right? So while a unique id would allow us to determine which objects need to be removed during that brute force scan, at the end of the day it would still be a brute force scan :)

This isn't something which would be a natural fit for CQEngine, which is optimized for performance.

I think the way forward, is to have a mechanism which intercepts modifications as they are being made to objects, and notifies CQEngine of the impending modification. In other words, a proxy-like mechanism which I discussed above. The proxy can remove the object from the collection before the change is made, and re-add it to the collection after the change has been made.
