### ISSUE TITLE
Can we Index Wrapper Class

### ISSUE THREAD

**Issue by jasgeeteden** [npgall/cqengine#174]
When I do this

 public static final Attribute<OrderBook, Market> MARKET = new SimpleAttribute<OrderBook, Market>("market_id") {
        @Override
        public Market getValue(OrderBook o, QueryOptions queryOptions) {
            return o.market;
        }
    };

then i can't do this

infoIndexedCollection.addIndex(NavigableIndex.onAttribute(OrderBook.MARKET));

**Comment by npgall** [comment]
Yes you should be able to do that. What error do you get? Is it a compilation error?

If you are getting a compilation error then it's probably because you need to ensure your Market class implements the Comparable interface if you want to build a NavigableIndex on it. 

The NavigableIndex is only compatible with attributes which are Comparable. This is because it's an ordered index, and to support range queries it needs to compare one value with another.

If Market cannot implement the Comparable interface, then you can use it with a HashIndex instead. That index works with any type of object, but it supports only equality lookup, and it does not support range queries.

I'd recommend that you implement equals() and hashCode() in your wrapper objects too if you have not done so already. It's not an absolute requirement but it is recommended practice when storing such objects in collections.
