### ISSUE TITLE
Wrong resultSet.size() returned for query without specifiing dedup.strategy

### ISSUE THREAD

**Issue by turja12** [npgall/cqengine#175]
Hello, 
In our app, we are not using explicitly deduplication strategy as queryOption, we are always asking CQEngine for returning sorted results and this operation is not returning duplicates. 
Because of paginition we need also return total number of results which can be returned by this query. 
We were using resultSet.size(), which should return us this number. 

If query should containt duplicates, but these are not returned because of sorting, we are getting total count from resultSet.size() with duplicates. 
When we turn on deduplication strategy (no matter which of them) then resultSet.size() is correct. 

Below is sample application: 
```
public class Pokus {

    public static void main(String[] args) {
        Pokus cqTest = new Pokus();
        cqTest.runMe();
    }

    public void runMe() {
        //this query should fords with id == 1, or fords with 5 doors everything
        Query<Car> query = or(
                and(
                        equal(Car.MANUFACTURE, "Ford"),
                        equal(Car.ID_ATTR, 1)),
                and(
                        equal(Car.MANUFACTURE, "Ford"),
                        equal(Car.DOORS_ATTR, 5))
        );

        IndexedCollection<Car> indexedCollection = new ConcurrentIndexedCollection<>();
        indexedCollection.addIndex(NavigableIndex.onAttribute(Car.MANUFACTURE));
        indexedCollection.addIndex(NavigableIndex.onAttribute(Car.ID_ATTR));
        indexedCollection.addIndex(NavigableIndex.onAttribute(Car.DOORS_ATTR));

        indexedCollection.add(new Car("Ford", 1,5));
        indexedCollection.add(new Car("Ford", 2,3));

        DeduplicationOption deduplication = deduplicate(DeduplicationStrategy.LOGICAL_ELIMINATION);
        ResultSet<Car> results = indexedCollection.retrieve(query, queryOptions(
                orderBy(ascending(Car.ID_ATTR)),
                applyThresholds(threshold(INDEX_ORDERING_SELECTIVITY, 0.9)),
//                deduplication,
                new QueryLog(System.out)));
        System.out.println("\nCars returned from store: ");
        streamOf(results).forEach(System.out::println);     //There should be just one car
        System.out.println("Number of cars in resultSet.size: "+ results.size());   //This should return 1 but it is returning 2
        System.out.println("Number of cars in streamOf(resultSet).count(): "+ streamOf(results).count());   //This should return 1
```
```
@Getter
@ToString
public class Car {
    public static final SimpleAttribute<Car, Integer> ID_ATTR = new SimpleAttribute<Car, Integer>("id") {
        public Integer getValue(Car car, QueryOptions queryOptions) {
            return car.getId();
        }
    };

    public static final SimpleAttribute<Car, Integer> DOORS_ATTR = new SimpleAttribute<Car, Integer>("doors") {
        public Integer getValue(Car car, QueryOptions queryOptions) {
            return car.getDoors();
        }
    };

    public static final SimpleAttribute<Car, String> MANUFACTURE = new SimpleAttribute<Car, String>("manufacture") {
        public String getValue(Car car, QueryOptions queryOptions) {
            return car.getManufacturer();
        }
    };

    private final String manufacturer;
    private final int id;
    private final int doors;


    Car(String manufacturer, int id, int doors) {
        this.manufacturer = manufacturer;
        this.id = id;
        this.doors = doors;
    }
}
```

And there is output from this sample app. 
```
indexForOrdering: NavigableIndex
queryCardinality: 2
indexCardinality: 2
querySelectivity: 0.0
selectivityThreshold: 0.9
orderingStrategy: index

Cars returned from store: 
Car(manufacturer=Ford, id=1, doors=5)
Number of cars in resultSet.size: 2
Number of cars in streamOf(resultSet).count(): 1
```

**Comment by npgall** [comment]
This is actually the expected behavior. You just need to request deduplication if you actually need it.

The following is an excerpt from the [release notes for CQEngine 2.5](https://github.com/npgall/cqengine/blob/master/documentation/ReleaseNotes.md#version-250---2016-05-06) where the behaviour here changed.

### Version 2.5.0 - 2016-05-06 ###
...
* The deduplication characteristics of ResultSet.size() has been changed, when ordering is requested but deduplication is not requested:
  * Previously, if a query requested that the results were to be ordered, but it did not request that they were to be deduplicated as well: the ResultSet.iterator() would return ordered and deduplicated results AND the ResultSet.size() method would reflect the outcome of that deduplication in its calculation of size too.
  * Now, if a query requested that the results are to be ordered, but it does not request that they are to be deduplicated as well: the ResultSet.iterator() will return ordered and deduplicated results as before BUT the ResultSet.size() method will not reflect the outcome of that deduplication in its calculation of size, and the size returned may count duplicate objects.
  * **This change makes the calculation of size() faster when the application wants results to be ordered, but doesn't care about deduplication per-se, or when the query would not produce duplicates anyway.**
  * The previous behaviour can be reinstated by requesting both ordering and deduplication.
  * In general, applications which want deduplication should request it explicitly, and they should not rely on the fact that ordering results sometimes provides deduplication as well.

---
Basically the rationale is that deduplication is expensive and not always required for the computation of `ResultSet.size()`. 

There is a "fast path" and a "slow path". Without deduplication, CQEngine can use a fast path to compute the `size()` from indexes. However when deduplication is required, that approach is not possible and the slow path will always be used. Essentially this tradeoff is similar to the difference between "SELECT" and "SELECT DISTINCT" in SQL.

It's not really possible to know in advance if a query will produce duplicates because it's application and query/data dependent. So that change was made to allow the developer to choose (based on their domain knowledge) whether deduplication is required on a query-by-query basis.

## Scalability considerations ##

Re: _"Because of paginition we need also return total number of results which can be returned by this query."_

Beware that this requirement might not scale well. This design often works fine in small systems, but does not scale to larger systems.

The latency of `ResultSet.size()` with deduplication enabled, will be proportional to the number of results matched by the query. If the number of results matched by each query might increase over time in your application, then this could indicate scalability issues in future.

However - that said - the scalability is proportional to the number of results which match the query - _O(r)_  - not to the size of the collection per-se -  _O(n)_ . So if your queries are inherently limited somehow in the number of items from the collection they can match (i.e. your _O(r)_ is bounded), then that's fine.

I think it's quite an expensive proposition to compute a count of deduplicated results, just for the sake of pagination. To give an idea: computing the number of matching results, is often much more expensive than retrieving the first page of actual results.

If you do think this might cause scalability issues, then I'd recommend to avoid a pagination system which needs to compute the count or number of pages which match a query. A system which shows an estimate such as "100+ results", and links to go to "next page" instead of page "57" is faster and more scalable.

You'll note that Google does not accurately compute the number of items or number of pages for its search results, and they have no reservations about suggesting that more pages of results exist which match the query, than they actually return when you navigate through the pages. It's undoubtedly for reasons like this.

**Comment by turja12** [comment]
Thanks for answering my question, I am writting a bit late because of holidays, sory for that. 
 
Maybe you should enhance a doc a bit, I was not able to find description of this behaviour in documentation. But Maybe I just missed it and it is somewhere documented (I mean somewhere else then in release notes). 

Big thanks also for that scalability considerations, we are currently aiming to something like 500K records in CQE, but probably on many customers site it will be much less. But when we will have some spare time on project we will try to do some benchmarking for our case and maybe we will change that design accordingly to your recommendation.

**Comment by npgall** [comment]
You are right that the documentation was actually incorrect on this - thanks!
It referred to the pre-CQEngine 2.5 behavior. 

I have updated it. I think it should now hopefully be clear to new users at least, that applications should request deduplication if the need it, because it is no longer mentioned that ordering would also eliminate duplicates in the documentation.

Best regards,
Niall
