### ISSUE TITLE
Generate attributes from private class fields

### ISSUE THREAD

**Issue by josdejong** [npgall/cqengine#181]
When implementing `cqengine` in our application, I initially couldn't get the parser working: no attributes where found by `AttributeBytecodeGenerator.createAttributes` on the POJO's we're using:

```java
SQLParser<Car> parser = SQLParser.forPojoWithAttributes(Car.class,
    AttributeBytecodeGenerator.createAttributes(Car.class)); 
```

It turns out that it didn't work because the fields in our POJO where defined `private`. When changing this to `protected`, everything works fine. Now I really like this solution of automatically finding all fields of a POJO, it's much better than manually creating and registering attributes via `parser.registerAttribute`. 

Would it be possible to have `AttributeBytecodeGenerator.createAttributes` find private class fields too? I think that it's quite a common case with Java POJO's.

**Comment by npgall** [comment]
There's a short answer and a long answer :)

**The short answer**
The short answer is, you can either use bytecode generation to access getter methods instead of private fields, OR you could use reflection instead. 

Since CQEngine [2.12.2](https://github.com/npgall/cqengine/blob/master/documentation/ReleaseNotes.md) you can use [AttributeBytecodeGenerator](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/codegen/AttributeBytecodeGenerator.html) to generate attributes which read from getter methods instead of, or as well as, fields. So if you have a typical POJO where the fields are private but the getter methods are public, then this should work fine.

Alternatively, if you need to access private fields, you can do so relatively easily via reflection. For this you could take a look at [ReflectiveAttribute](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/attribute/ReflectiveAttribute.html) which does support private fields. Reflection is much faster than it used to be, but it will probably be marginally slower than the bytecode approach.

**The long answer**
The long answer is it's [not easy](https://ruediste.github.io/bytecode/2017/02/23/generate-private-field-setter.html) to generate bytecode which will read the value of a private field. The `private` access modifier basically tells the JVM to make that as difficult as possible!

Currently CQEngine's `AttributeBytecodeGenerator` works by generating attribute classes which are in the same package as the POJO. This way they can access fields which have any access modifiers [except private](https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html) (this include package-private i.e. fields with no access modifier too).


Hope that helps!
Niall

**Comment by josdejong** [comment]
Thanks for the clear explanation Niall. I can certainly understand that it's not trivial to extract private fields in a reliable way. 

I am using `AttributeBytecodeGenerator` right now a try, we do have standard POJO's with getters and setters but I couldn't get that working, maybe I overlooked something. I've changed our POJO's to have protected fields instead of private, so the problem is solved for us, but having cqengine be able to work with more types of POJO's would simply be a great enhancement.

An other solution can be to utilize Jackson, which did all this hard work already for us: serialize a Car instance to a JSON string, parse that again into a Map, and read the keys of the map ;)
```java
Car exampleCar = new Car(...);
ObjectMapper mapper = new ObjectMapper();
Map<String, Object> carMap = mapper.readValue(mapper.writeValueAsString(exampleCar),
        new TypeReference<HashMap<String,Object>>() {/*intentionally empty*/});

System.out.println("All fields: " + carMap.keySet());
```

**Comment by npgall** [comment]
If you want to generate attributes for getters, you actually need to request it explicitly via [this method](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/codegen/AttributeBytecodeGenerator.html#createAttributes-java.lang.Class-com.googlecode.cqengine.codegen.MemberFilter-), using one of the [MemberFilters](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/codegen/MemberFilters.html).

Hope that helps!

**Comment by josdejong** [comment]
Thanks that indeed helps, I wasn't aware of the `MemberFilters`. I think what I would need to have cqengine working with private fields is `MemberFilters.GETTER_METHODS_ONLY`. This works but is not practical right now:

```java
SQLParser<Car> parser = SQLParser.forPojoWithAttributes(Car.class,
    AttributeBytecodeGenerator.createAttributes(Car.class, GETTER_METHODS_ONLY)); 

// The following will not work:
//  SELECT * FROM cars WHERE (price <= 5000.0)

// what does work is:
//  SELECT * FROM cars WHERE (getPrice <= 5000.0)
```
I understand what happens, you have to put the getter name `getPrice` in the SQL query instead of the field name `price`, but it's not really practical from a user point of view... 

Am I overlooking something?

**Comment by npgall** [comment]
This is now implemented.

You can now do this:

```
SQLParser<Car> parser = SQLParser.forPojoWithAttributes(Car.class,
    AttributeBytecodeGenerator.createAttributes(Car.class, GETTER_METHODS_ONLY, USE_HUMAN_READABLE_NAMES_FOR_GETTERS)); 
```

**Comment by josdejong** [comment]
Thanks @npgall !
