### ISSUE TITLE
Clear Index before addIndex

### ISSUE THREAD

**Issue by lelmarir** [npgall/cqengine#188]
Hi,

today, a little naively, i've wrote something like this:

`collection.getIndexes().forEach(i -> collection2.addIndex(i));`

my goal was to create a second collection with the same indexed i have configured for the first.
This however cause the second collection to literally use the indexes from the first, thus returning items from it instead of rebuilding the same filters from the later.

The addIndex method should throw exception when adding a "dirty" index or (even better) create a copy and clean it.

Hope this may help 

ps. any way to achieve this? (configuring the same index for a second collection)

**Comment by npgall** [comment]
It's a good question!

The best way to clone an IndexedCollection and the contents of it's indexes, is to create a new IndexedCollection and configure the new one with the same types of indexes, and then call `secondCollection.addAll(firstCollection)`.

The reason you see the other behavior is because the indexes are actually somewhat self-contained, and they are responsible for maintaining their own state. The IndexedCollection.addIndex() method just registers the index with a collection, and subscribes it as a listener to changes in the collection.

I think I should add this info to the FAQ because it's a fair question. I'll keep this issue open as a reminder until that's done. Thanks!

**Comment by lelmarir** [comment]
ok, thank you,
but i think it would be useful if addIndex, at least, throw an exception if the index is dirty,
is this possibile?

**Comment by npgall** [comment]
I have not been able to think of a better solution to this I'm afraid. So for now I think it's best to retain the current behaviour. I will close this for now, but feel free to reopen if you need more info!
