### ISSUE TITLE
How to calculate collection size ?

### ISSUE THREAD

**Issue by albert-kam** [npgall/cqengine#194]
Hello ..

Do you guys have any suggestions on how to to roughly calculate the size of any IndexedCollection in the Java Heap ?
Even better, perhaps even include the calculation of average object size in the collection.

**Comment by npgall** [comment]
This is supported for disk and off-heap persistence - `persistence.getBytesUsed()` - but I'm afraid it's not supported for the on-heap persistence. 

This is because it's just quite difficult to determine the size of on-heap object graphs.

My only suggestion is to, on a non-production system, run `System.gc()`, measure heap usage, populate a collection, run `System.gc()` again, and measure heap usage again. Then calculate the delta in heap size. This will give you an idea of heap memory usage used by that particular collection.

If you know of a better way this can be done, please let me know!
