### ISSUE TITLE
Add ability to limit number of results

### ISSUE THREAD

**Issue by GoogleCodeExporter** [npgall/cqengine#20]
```
See discussion in forum: 
https://groups.google.com/forum/#!topic/cqengine-discuss/o4oUCc-PGOA

It would be nice if CQEngine had an explicit way to limit the number of results 
returned. Currently, the application can just stop iterating when it has enough 
results. But built-in support might be useful as an alternative.

Possible approach:

ResultSet<Car> results = cars.retrieve(equal(Car.MANUFACTURER, "Ford"), 
queryOptions(limit(20)));

However, then support for pagination would seem like a good idea, but the limit 
approach would be inefficient as it would require re-starting the query for the 
second page.

Efficient pagination approach:

ResultSet<Car> results = cars.retrieve(equal(Car.MANUFACTURER, "Ford")); // 
cache this
for (Car car : Pagination.limit(results, 20)) { // Advances through the first 
20 cars
    // Process the first 20 cars
}
for (Car car : Pagination.limit(results, 20)) { // Advances through the next 20 
cars
    // Process the next 20 cars
}
```

Original issue reported on code.google.com by `ni...@npgall.com` on 28 Aug 2013 at 1:38

**Comment by npgall** [comment]
Closing this issue as this problem is best solved by combining other libraries with CQEngine.

CQEngine's ResultSet implements the java.lang.Iterable interface, therefore results can be limited or paginated as follows:
* Guava's [Iterables.limit()](https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/collect/Iterables.html#limit(java.lang.Iterable,%20int))
* Convert the CQEngine ResultSet into a Java 8 Stream and call [Stream.limit()](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#limit-long-)
* Consider using a variety of open source pagination libraries.

**Comment by DuskoV** [comment]
Please open this issue. Here is the reasoning:

Records: 100k

SQL:
SELECT * FROM Cars ORDER BY color LIMIT 10

cqengine will sort and return all 100k records (2+ seconds), and then other libraries should paginate.

If SQL parser considers LIMIT keyword and finds defined index (HashIndex on int), it would be natural to optimize response to top 10 results by HashIndex.

As a result, query will be in a ms instead of sec.

**Comment by npgall** [comment]
Actually what you probably need is a NavigableIndex on price (i.e. not a HashIndex), and to request CQEngine to use the "index" ordering strategy. Take a look at: [OrderingStrategies.md](https://github.com/npgall/cqengine/blob/master/documentation/OrderingStrategies.md)

If you need more help with this, feel free to open a new issue and we can continue discussing there. Hope that helps for now!

**Comment by ale3hs** [comment]
Create a limitBy option, add it to the queryOptions. Create your own version of MaterializedOrderedResultSet that only sorts the top n of the resultSet and just appends the rest to the bottom of the data structure. Upon iterator(), read that limit and sort accordingly. This way you'll have a "list" of resultset.size where the top n are sorted (given that you don't care about n+1...) rather than using the treeSet to sort the entire result set. Any item that compares > to the nth item is just added to the bottom of the semi-sorted structure. You could also use a variation of the binary search to reduce the complexity of finding where to insert an item in the top n. Try it out by sloppily overriding MaterializedOrderedResultSet in your project path with hard-coded limits, if it works out for you build your own queryEngine etc

**Comment by ale3hs** [comment]
great work btw @ npgall

**Comment by muhdkhokhar** [comment]
please someone give me a example how to achieve pagination
