### ISSUE TITLE
Why each index's attribute creates a table when using DiskIndex

### ISSUE THREAD

**Issue by Yrp** [npgall/cqengine#201]
Hi, @npgall,
Now I use DiskPersistence, and found that each attribute will create a SQLite table. Why each index's attribute creates a table?  The primary key will store multiple copies on the disk, it will take some space.
Another solution, such as each attritute corresponding to a column in a table is feasible？

**Comment by Yrp** [comment]
Thank you for providing such a good library.

**Comment by npgall** [comment]
Hi @Yrp it's a good question and you are correct, that's how it's implemented.

This design is because CQEngine supports multi-value attributes. It would be possible to use regular columns in a single table for attributes which have 0 or 1 value, but not if they can have more than one value.

Hope that helps!
Niall
