### ISSUE TITLE
Disk mode serializes object instead of using primary key

### ISSUE THREAD

**Issue by andrew-barkley** [npgall/cqengine#211]
I am very comfortable with code using the default ConcurrentIndexedCollection constructor, but creating with DiskPersistence does not behave as expected.  The primary key attribute is not used as expected, and instead the full object is kryo serialized instead of just the key attribute.  That means that modify and remove operations require the original object (or serialized equivalent) to behave as expected.

**Comment by npgall** [comment]
Yes that's true. However that behavior is expected because if you create the ConcurrentIndexedCollection supplying DiskPersistence to its constructor, this is how you configure it to persist/serialize the objects in the collection to disk. Or am I misunderstanding something?

If you configure it like that, it's true that you need to supply the full object to the collection to remove it. If you don't have the object and you only have its primary key, you can retrieve() the object from disk using on its primary key first. CQEngine will need the full object either way, because if you have other indexes, CQEngine will need to reads other fields in the object to remove it from those indexes too.

If you just want to store one index on disk but to leave the collection itself on heap (i.e. you don't want to serialize the objects at all), then you need to use CompositePersistence.of(OnHeapPersistence, DiskPersistence). That way your objects will not be serialized to disk, but your disk index will be stored to disk.

**Comment by muhdkhokhar** [comment]
I don't really understand why you have to do.
Because I am having problem deleting the items.
My value is a object that has a generic list and sometimes list can be have sub list as well 

if I have alot of objects the delete doesn't even work.

how can I delete using the key which will be very quickl?

**Comment by muhdkhokhar** [comment]
How can I make my code to work with SimplifiedSQLiteIndex
