### ISSUE TITLE
Query to test existence of multiple value in MultiValueAttribute 

### ISSUE THREAD

**Issue by victornoel** [npgall/cqengine#214]
Hi,

I was trying to do something and couldn't find a way to do it, so I wonder if I'm missing something or it is a missing feature.

I store objects with an attribute that is a collection of strings (they are tags).

So I defined a `MultiValueAttribute` for it, so that I can find objects with one of the tags using `QueryFactory.equal`.

Until then everything is ok, but if I want to find an object with TWO different tags, I just can't.

In a way, I'm looking for the complement of `QueryFactory.in` where I want to test that the attribute contains all the string in the query.

**Comment by npgall** [comment]
Good question.

You should be able to solve this by creating a complex query which looks like `and(equal(), equal(), equal())` where each of the equal() queries checks for a specific tag.

Would that work for you?

**Comment by victornoel** [comment]
@npgall ok, I thought about it but I was wondering if performance-wise, this would work as expected. If not, I suppose that we need a specific operator, if yes I think we can close this :)

**Comment by victornoel** [comment]
@npgall for the record, `and` does not support only one element, so I found myself writing this kind of code:
```
        Iterator<String> it = tags.iterator();
        if (!it.hasNext()) {
            return db.retrieve(all());
        } else {
            String first = it.next();
            if (!it.hasNext()) {
                return db.retrieve(equal(this.tags, first));
            } else {
                String second = it.next();
                return db.retrieve(and(
                    equal(this.tags, first),
                    equal(this.tags, second),
                    Seq.seq(it).<Query<Row>>map(t -> equal(this.tags, t)).toList()));
            }
        }
```

That's not sexy at all :)

**Comment by npgall** [comment]
`and` does not support only one element, but that's because it does not make sense in terms of logic or intersection of sets. It would be equivalent to the query itself.

If you would like to simulate an `and` query with one element in your application though (say for consistency), you could add a static method to your application as follows. 

It can augment the other (non-singular) `and` methods from `QueryFactory` if you add a static import for this additional method as well.

```java
public static Query<O> and(Query<O> query) {
    return query;
}
```

**Comment by victornoel** [comment]
@npgall I understand, but if you look at my example, your solution won't help, since I am looking to implement a query that can generically handle 0, 1 or N elements with `and`.

I think it would be acceptable that the `and()` method provided by cqengine would:
- take any number of arguments
- delegates to:
  - `all()` if there are zero argument
  - the sole argument if there is exactly one argument
  - the current behaviour if there are more than 1 argument

This would be a not breaking change I think and would simplify the API from the user point of view.

Here is a tentative implementation:
```java
public static <O> And<O> and(Query<O>... queries) {
    if (queries.length == 0) return all();
    if (queries.length == 1) return queries[0];
    return new And<O>(queries);
}
```

**Comment by npgall** [comment]
Yes that approach should work well if you implement a method like that in your application.

As I mentioned this is not something I'd like to integrate directly into CQEngine though, because I want to preserve the requirement that `and()` queries must have at least 2 child queries. 

The main reason is that it can be ambiguous as to how an `and()` query with 0 child queries should be evaluated; some applications might want it to be treated as an `all()` query, and other applications might want it to be treated as a `none()` query. 

An `and()` query which has exactly 1 child query, would be equivalent to that child query itself. So I feel it will be simpler for CQEngine's internal logic if it can avoid having code paths to handle these two ways of expressing the same thing.

So I think the best solution is, for applications which want to support `and()` queries having 0 or 1 child queries, to just implement their own static helper method in the application as you have posted above - and then the application can customize the handling of 0 child queries per its requirements.

I hope that helps explain my thinking. Feel free to reopen if you would like to discuss other options.
