### ISSUE TITLE
Standing query for regex with parameter

### ISSUE THREAD

**Issue by MicleBrick** [npgall/cqengine#219]
In the javadocs, it says to use a standing query to improve regex performance. But is this possible when it's e.g. to search a case-insensitive name?

**Comment by npgall** [comment]
**Why a `StandingQueryIndex` is probably not what you want**

You can use a `StandingQueryIndex` to improve the performance of a single regex query.
So if you have a situation where the same regex query is performed a lot, then `SQI` will help.

However if you have lots of different regex queries coming in, then `SQI` will probably not help - unless you know what the queries are in advance so you can add an index for each one. This is often not realistic.

**Recommendation**
I guess you actually want to support case-insensitive lookup by names, and you don't know which names will be looked up in advance, right?  So in that case your best option is to:

1. Define your NAME attribute so that it converts your name field `.toLowerCase()`
2. Add an index on your NAME attribute
    * A `HashIndex` will support fast lookup given a complete name (use a `equal()` query)
    * A `RadixTreeIndex` will support fast lookup given a prefix of a name (use a `startsWith()` query)
3. Ensure that you convert the name you want to search for to lowercase, before you put it in the a `equal()` or  `startsWith()` query

This will give you fast case-insensitive lookups by names.

Hope that helps!
