### ISSUE TITLE
Performance Optimizations

### ISSUE THREAD

**Issue by archenroot** [npgall/cqengine#220]
Hi,

I am considering joining contest back in Russia regarding **high load services**:
https://highloadcup.ru/en/

I would like to use as backbone In-memory engine with disk persistence cqengine. 

The machine is limited to 4cores, 2GB Ram, 10TB storage and the testing uncompressed data set is size of 2,1GB .

Q: Do you have any production grade optimizations to get max throughput? Should I use JDK 8-11? etc. Any hint is well welcomed. My idea is that I will use only single index on ID and rest being stored on disk. Maybe I will store everything as byte[], but not sure if that can bring some improvement or not.

Ladislav

**Comment by npgall** [comment]
Sorry for the delay getting back to you here. I typically work on CQEngine in bursts :)

If you are looking to maximize throughput, typically I would suggest to use only the on-heap persistence and indexes, as these can be significantly faster than off-heap and disk-based indexes, due to the ability to return Java object references directly and avoid deserialization.

However, it sounds like that 2.1GB dataset will not fit in the 2GB RAM on the host(?) which could be a big problem there. So you might be forced to use DiskPersistence.

In the latest version of CQEngine, there is a shared_cache mode supported by DiskPersistence, which can improve read throughput quite a bit. You could find information on how to enable this, and a discussion of the tradeoffs, in the [JavaDoc](https://github.com/npgall/cqengine/blob/master/code/src/main/java/com/googlecode/cqengine/persistence/disk/DiskPersistence.java) for that class.

Apart from that if you can store data items on disk and the workload will not actually cause a significant number of items to be loaded, then you could look at using a combination of on-heap indexes with disk persistence.

If you will use disk-based indexes, also take a look at enabling the [index merge strategy](https://github.com/npgall/cqengine/blob/master/documentation/MergeStrategies.md) which can avoid the need to deserialize item values when processing queries.

With regards to JVM version (JDK 8-11) and also which garbage collector to use, usually JDK11 will be faster (because it uses G1 GC) but it can depend a lot on the traffic patterns, so it's worth experimenting.

Hope that helps. As always, experimenting is the best way to tune! Feel free to reopen if you need any more info.
