### ISSUE TITLE
Backup and replication

### ISSUE THREAD

**Issue by muhdkhokhar** [npgall/cqengine#222]
I am impressed by CQEngine. I want to replace MySQL database as its not performant.

If I use disk based how do I backup and replicate? 

If I still use MySQL how do I sync the data between the two

**Comment by npgall** [comment]
I would not recommend to use CQEngine as your primary database. It is designed to complement other databases, rather than to replace them. 

For example load some data from your primary database into CQEngine in your front end tier to answer hot queries faster etc.

CQEngine does not support replication itself.

**Comment by muhdkhokhar** [comment]
OK I understand the purpose now. I think I coudl look into Apache ignite to cache mysql database.
