### ISSUE TITLE
Navigable index is very slow

### ISSUE THREAD

**Issue by hirik** [npgall/cqengine#239]
If I missed anything please let me know

**Code**:

 final IndexedCollection<Field> indexedData = new ConcurrentIndexedCollection<>();
        indexedData.addIndex(NavigableIndex.onAttribute(Field.NUMBER));
        final int maxObjects = 10_000;

        long time = System.currentTimeMillis();
        for(int index = 0; index < maxObjects ;index++)
        {
            indexedData.add(new Field(index, "group"));
        }
        System.out.println("Insert - Time Taken by IndexedCollection: "+ (System.currentTimeMillis() - time));

        time = System.currentTimeMillis();
        for(int index = 0; index < maxObjects ;index++)
        {
            final Query<Field> query = and(greaterThanOrEqualTo(Field.NUMBER, index), lessThan(Field.NUMBER, maxObjects));
            final ResultSet<Field> resultSet = indexedData.retrieve(query);
            final long count = resultSet.size();
            if(count != (maxObjects - index))
            {
                System.out.println("Failed : index "+ index +", count: " + count);
            }
        }
        System.out.println("Search - Time Taken by IndexedCollection: "+ (System.currentTimeMillis() - time));

        final NavigableMap<Integer, Field> treeMap = new TreeMap<>();
        time = System.currentTimeMillis();
        for(int index = 0; index < maxObjects ;index++)
        {
            treeMap.put(index, new Field(index, "group"));
        }
        System.out.println("Insert - Time Taken by TreeMap: "+ (System.currentTimeMillis() - time));

        time = System.currentTimeMillis();
        for(int index = 0; index < maxObjects ;index++)
        {
            final SortedMap<Integer, Field> resultSet = treeMap.subMap(index, maxObjects);
            final long count = resultSet.size();
            if(count != (maxObjects - index))
            {
                System.out.println("Failed : index "+ index +", count: " + count);
            }
        }
        System.out.println("Search - Time Taken by TreeMap: "+ (System.currentTimeMillis() - time));

**Result :**
Insert - Time Taken by IndexedCollection: 271
Search - Time Taken by IndexedCollection: 19770
Insert - Time Taken by TreeMap: 12
Search - Time Taken by TreeMap: 792

**Comment by npgall** [comment]
You should use a `between()` query. 

CQEngine's query planner doesn't restructure the supplied query, to convert two `greaterThan()` and `lessThan()` queries into a single `between()` query. So you need to supply a `between()` query yourself, to properly take advantage of the `NavigableIndex`.

What's happening above, is the time complexity of your queries will be very high, possibly O(n^2) for the entire loop. It's because you're actually doing two different subqueries in each iteration, and finding the intersection of those two subqueries by combining in an `and()` query. 

The `lessThan(Field.NUMBER, maxObjects)` subquery is guaranteed to match all of the objects in the collection in every iteration (O(n)), so for n iterations, that's O(n^2) complexity. The `greaterThanOrEqualTo(Field.NUMBER, index)` subquery will initially match all of the objects in the collection as well (O(n)), reducing to O(1) by the last iteration. There will be a cost to find the intersection between the two subqueries in each iteration as well.

Let me know what results you get with a `between()` query!

**Comment by hirik** [comment]
Thanks for the update, After changing to "between" I got the result as below 

Insert - Time Taken by IndexedCollection: 87
Search - Time Taken by IndexedCollection: 2611
Insert - Time Taken by TreeMap: 8
Search - Time Taken by TreeMap: 545

It will be really helpful if you could share the best practice guide

**Comment by npgall** [comment]
That's closer to the performance that I would expect.

**For insertion**, I'd expect higher overhead with an IndexedCollection + 1 index, than for a single TreeMap on its own. That's because:
1.  With an IndexedCollection, there are two data structures to update: the Set which backs the collection itself and which stores all objects, and then the index.
    * This design (to maintain a separate Set of all objects) is necessary to be able to handle negated queries which might not refer to objects stored in indexes.

2. TreeMap is not a concurrent data structure, which means insertions into it may be cheaper than insertions into other data structures which do support concurrency.
    * The NavigableIndex is currently and by default backed by the [ConcurrentSkipListMap](https://github.com/npgall/cqengine/blob/master/code/src/main/java/com/googlecode/cqengine/index/navigable/NavigableIndex.java#L580) which is included in the JDK.
    * But you can actually configure NavigableIndex to use any [ConcurrentNavigableMap](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ConcurrentNavigableMap.html) implementation. Right now, ConcurrentSkipListMap is the only implementation of ConcurrentNavigableMap which ships with the JDK though.

3. A NavigableIndex will create a data structure which is like `ConcurrentNavigableMap<A, Set<O>>`. That is, a map where the keys are attribute values, and where the values of the map are Sets of objects which have those attribute values.
    * This enables the indexing of attributes which do not uniquely identify objects.
      * For example, a NavigableIndex on `Car.COLOR`, will assume that more than one car will be `BLUE`. So it will allocate a Set to store all of the BLUE cars. The same goes for all of the other colors.
    * In your example above, it looks like your `Field.NUMBER` attribute actually WILL uniquely identify objects. For that case, you would get the best insertion performance by using a [UniqueIndex](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/index/unique/UniqueIndex.html) instead of a `NavigableIndex`. 
      * The UniqueIndex differs from the NavigableIndex in two ways:
        * It does not allocate a Set to store objects for each of the attribute's values, instead it just stores the matching object directly in the index.
        * If (unfortunately) does not support range queries (`lessThan()`, `between()` etc.) because it is not backed by a NavigableMap. So UniqueIndex would not be able to accelerate your query above.
     * A middle ground for your use case, would be to look at configuring the NavigableIndex to use the [CompactValueSetFactory](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/index/hash/HashIndex.CompactValueSetFactory.html) which ships with the HashIndex. This would reduce the size of the Sets which are allocated inside your index, taking advantage of the fact that your attribute appears to uniquely identify objects.

**For search performance**, I'd also expect higher overhead from an IndexedCollection, than from accessing a TreeMap directly. If you're looking for the lowest possible latency for a lookup which is supported directly by a single data structure, your best bet will be to use that data structure directly. 

We expect some difference in the latencies because:
* The TreeMap is not a concurrent data structure as discussed above
* The TreeMap is not designed to handle arbitrary queries, so it does not have the overhead of identifying the available indexes which can best accelerate the query
* Your particular queries above are still going to be quite expensive, as they match the entire collection in the first iteration(s). 
  * I guess we could say, CQEngine is better optimized for finding a needle in a haystack (a relatively small number of matching objects in a large collection), than fetching every individual piece of straw in turn from the haystack 😄

**Comment by hirik** [comment]
@npgall  thanks for the clear explanation 😄, I was just running initial performance steps to check the iteration cost. Our case is different than this, we need to find a pattern in a collection.

And we are currently using the combination of concurrentSkiplistmap, Councurrenthashmap, CopyOnWriteArrayList.

**Comment by hirik** [comment]
Hi, Is it possible to query Map inside an object, 

    private final Long id;
    private final Map<Long, String> keyValue;

How can convert this statement to IndexedCollection Query

>  id > 10 && keyValue.get(2L).equals("test")
