### ISSUE TITLE
Executing Delete Query on Disk persistence

### ISSUE THREAD

**Issue by muhdkhokhar** [npgall/cqengine#246]
Hi

First of all I would like to say thanks a lot . Thsi library is turning out to be best ever for storage and as well for filtering data.

I am using Diskpersistence to save my data flow (Unblievable it takes less space with alot of data)

How can I delete the data first from the disk based on the index.

lets say

Runs 

RunId
List anyData

before putting the data into disk persistence how can I say remove all the data from the runID =1

can I execute delete ?

**Comment by npgall** [comment]
I'd suggest to add a timestamp field, and then create an attribute which reads that field. Then add a DiskIndex on that attribute.

You can then retrieve the objects older than (now - some time ago), and remove them from the collection. 

While that will work, it is not perfect because it does involve retrieving the objects you are about to delete. But that is necessary in order for CQEngine to remove each object from all of the indexes it might be mentioned in.

**Comment by muhdkhokhar** [comment]
Thanks. So do I have to just do 

collection.remove(object).

Will that remove from the disk automatically?

**Comment by npgall** [comment]
Yes :)

**Comment by muhdkhokhar** [comment]
Thanks a lot. Believe me your library is just under-rated. Its too good.

**Comment by muhdkhokhar** [comment]
Is there any example I can find to apply query on the Date index like less than x days?

**Comment by npgall** [comment]
I'd recommend to use [unix time](https://en.m.wikipedia.org/wiki/Unix_time) where you represent time as elapsed seconds since 1970. That way, it will just be an integer.
