### ISSUE TITLE
Polymorphic is not working

### ISSUE THREAD

**Issue by muhdkhokhar** [npgall/cqengine#256]
I am using the disk persistence 

lets say I have data in the disk already now I deploy new version of same code when I access the old data i get error

Failed to deserilize object 
object type: XXXXXX  configure @PersistenceConfig.polymorphic 
If the collection will contain a mix of objec types
Use Kryotserializer

This is causing big problems now.

**Comment by npgall** [comment]
That's not really what `polymorphic` is for, it's an instruction to save the name of the class along with the serialized bytes, so CQEngine will know which class to deserialize bytes to, if your collection contains a mix of object types.

What you are dealing with here is backward/forward compatibility issues of your serialized objects, when you add/remove new fields in future.

CQEngine is delegating entirely to Kryo to manage that. You can read about this topic on the [Kryo site](https://github.com/EsotericSoftware/kryo/blob/master/README.md#compatibility). 

If you can get your objects to serialize/deserialize in a backward and forward compatible way with Kryo alone, then that approach should be compatible with CQEngine too. That might involve adding Kryo annotations to your classes or fields in your classes to configure the specific Kryo serializers to use at class or field level.

Note also that CQEngine is at the whim of Kryo for the backward/forward compatibility situation. Kryo's own rule of thumb is that if the major software version of the Kryo library is changed, the new version will not be able to deserialize objects saved with an older version. 

This caused a problem for CQEngine in the past, because an older version of Kryo was not compatible with Java 11. So I made a new release of CQEngine which bumped the version of Kryo used. That made CQEngine compatible with Java 11, but broke backwards compatibility with older saved objects. I endeavour to bump the major version of CQEngine when upgrading to new versions of Kryo.

**Comment by npgall** [comment]
So in summary: within the same major version of CQEngine + Kryo, you can follow Kryo documentation to ensure compatibility if you add fields. 

But that won't work between major versions.

**Comment by muhdkhokhar** [comment]
That is a big flaw in itself? I am using disk persitence for reconciliation reporting

Lets say i save the data for the week now next week we deploy new version now i won't be able to retrieve week older data 

I never thought that would be such problem

What are the optios available for me now to make it work?

**Comment by muhdkhokhar** [comment]
Is it ok if I annotate the classes with CompatibleFieldSerializer as it will be compatible in future?

**Comment by npgall** [comment]
It is you who is breaking the backward/forward compatibility of your objects there actually, if you add or remove fields and then try to deserialize older formats. To solve that, you just need to be aware of what's needed to add/remove fields in a backward compatible way, by reading about this on the Kryo site. It's definitely possible to evolve your objects without breaking compatibility. 

I'm just calling out as well, that there is not much that can be done at the CQEngine side to make that easier - except that I try to document any backwards incompatible changes in the CQEngine release notes.

If any new version of CQEngine will break compatibility with an older version, it will be mentioned in the release notes. The major version number of CQEngine will usually be incremented in those cases too. 

So I'd just recommend to not upgrade to any major new version number, without reading the release notes first. But this applies to any major new version of software actually.

It's not really a flaw, this is the best that can be done at the CQEngine side. If you have any better ideas, I'm open to suggestions and contributions are welcome.

**Comment by npgall** [comment]
Just to add as well, you can plug in any serializer you like to use with CQEngine. So if you find that a different serializer works better for you than Kryo, you can add a @[PersistenceConfig](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/persistence/support/serialization/PersistenceConfig.html) annotation to your objects to configure that.

**Comment by muhdkhokhar** [comment]
Thanks. I understand the issue. I'll take a shot with CompatibleFieldSerializer  hopefully that works.

**Comment by npgall** [comment]
Closing this. Feel free to reopen if you need more help.
