### ISSUE TITLE
Query creation performance

### ISSUE THREAD

**Issue by glockhart** [npgall/cqengine#259]
I'm investigating using CQEngine as an Decision Table implementation.  In particular I'm comparing CQEngine to the Drools Decision Table implementation.

While Drools is very feature rich I don't need all of the features it provides, but I do need better performance.

When using CQEngine to model a decision table, I end up with a *lot* of queries to generate.  Worst case, for every row create an AND query with a sub-query for each of the cells.

I've got a working example, but the performance difference with Drools isn't very much (and in cases of large tables CQEngine performs worse).

After running a profiler I can see that the issue isn't actually with running the queries, but with creating them in the first place.

Give that there may be 1000's of queries, the sheer overhead of creating them all is more than the time taken to run them. 

So I started thinking about how I could use the equivalent of a prepared statement and create the query once and then bind the actual values just before executing ::retrieve

Effectively I want to do something like this

```
    @Test
    public void testWithModifiableQuery() {
        ValuePlaceHolder<Integer> ph = new ValuePlaceHolder<>(1);
        //create the query once (and only once)
        Query<Car> query1 = new Equal<>(Car.CAR_ID, ph);
        ResultSet<Car> resultSet = cars.retrieve(query1);
        assertEquals(1, resultSet.iterator().next().carId);
        
        //update the query placeholder value we want to use
        ph.setValue(2);
        resultSet = cars.retrieve(query1);
        assertEquals(2, resultSet.iterator().next().carId);
    }
```
To enable this to work I had to make 2 changes to CQEngine

- Add the ValuePlaceHolder class to com.googlecode.cqengine.query.simple

- Modify the Equal class to use the ValuePlaceHolder instead of the raw value

```
public class Equal<O, A> extends SimpleQuery<O, A> {

    private final ValuePlaceHolder<A> value;

    public Equal(Attribute<O, A> attribute, A value) {
        super(attribute);
        this.value = new ValuePlaceHolder<>(checkQueryValueNotNull(value));
    }
    
    public Equal(Attribute<O, A> attribute, ValuePlaceHolder<A> value) {
        super(attribute);
        this.value = value; //checkQueryValueNotNull(value);
    }

    public A getValue() {
        return value.getValue();
    }

    @Override
    public String toString() {
        return "equal("+ asLiteral(super.getAttributeName()) +
                ", " + asLiteral(value.getValue()) +
                ")";
    }
    ......
```
Based on my testing this improves my performance from ~1ms to ~0.002ms for my decision table test case (creating 1000 AND queries with 2-5 sub clauses / queries. e.g. 1000 of these
```
and(equal("index", 1223), equal("foo", "12504"), equal("bar", "xxxx"), equal("baz", "yyyy"))
```

While this works as a proof of concept there would be a lot more work needed in terms of updating the rest of the Query types and testing the whole thing.  I'd probably also need to update the QueryFactory to correctly create the queries (it doesn't work properly in my POC code yet)

Before I do that work I thought I'd see if this was a feature you'd be interesting in having added @npgall ?

**Comment by npgall** [comment]
Sorry for the delay. I am planning to set aside some time to work on CQEngine next week and I'll think about it in more detail then. The following are some initial thoughts.

What comes to mind is that some rules engines use something like the [Rete algorithm](https://en.m.wikipedia.org/wiki/Rete_algorithm) to identify which rules need to fire. CQEngine internally (of course) doesn't implement an algorithm like that, but a different algorithm which is optimised for retrieving objects which match queries. 

With the Rete algorithm the rules are static and data is fed into it. For CQEngine it is somerimes the other way around, the data may be (somewhat) static, and the queries on that data can vary. So I don't know if CQEngine would be optimised for that kind of thing. (I'm not an expert on the Rete algorithm btw)

Another thing to bear in mind is that CQEngine is quite widely used now, and we need to be careful about making any changes which are not backward compatible. So that means we need to avoid changing existing API behavior. For example the QueryFactory currently creates immutable queries.

Immuability has advantages (thread safety, and preservation of invariants) and disadvantages (the need to create new instances all the time, and the difficulty to recycle the same query objects between different requests). We also need to balance the benefit that introducing mutable queries would bring for a subset of users, with the increased complexity it might introduce into the engine. It's hard to know in advance where the cost-benefit would land. 

If we introduce mutable queries I think we could do so via a MutableQueryFactory class or similar. Perhaps both types of queries could then implement a common interface, and then CQEngine's engine would work equally well with both. That approach would solve both concerns.

If you'd like to do a POC, it would be interesting to see the results.

**Comment by glockhart** [comment]
I've been doing more work on this on the side and it looks like CQEngine won't really be suitable for this after all.  We've been able to get more predictable performance out of the rules engine for this one use case so I think we're going to go that way instead of trying to use CQEngine for something it's not really designed for.  

We'll still be using CQEngine for other jobs in out products
