### ISSUE TITLE
attribute register

### ISSUE THREAD

**Issue by Zzzwenjie** [npgall/cqengine#264]
Code: 
       IndexedCollection<CloudMetaData> data = new ConcurrentIndexedCollection<CloudMetaData>();
        data.add(new CloudMetaData("aaa","aaa",null));

        SQLParser<CloudMetaData> metaDataSQLParser = SQLParser.forPojoWithAttributes(CloudMetaData.class, AttributeBytecodeGenerator.createAttributes(CloudMetaData.class,GETTER_METHODS_ONLY,
                USE_HUMAN_READABLE_NAMES_FOR_GETTERS));

        ResultSet<CloudMetaData> results = metaDataSQLParser.retrieve(data, "select * from data where regionId = 'aaa'");
        results.forEach(System.out::println);
-------------------------------------------------------------------------------
Error:
Caused by: java.lang.IllegalStateException: No such attribute has been registered with the parser: regionId

--------------------------------------------------------------------------
Details:
  The pojo's defined with private fields.
  if i register a attribute to the the parser by the metaDataSQLParser.registerAttribute();,it's work.
 but if i don't register the attribute but only do like the code above ,it will thorw the error above.
 i'm wondering if i missed something?or it's just the design to do this?
 should i only use it by register a attribute to the parser?

**Comment by Zzzwenjie** [comment]
hello.I'm wondering is AttributeBytecodeGenerator.createAttributes doesn't support the autocreate of MAP?

**Comment by npgall** [comment]
There's couple of issues there.

The first is that you are specifically requesting AttributeBytecodeGenerator to generate attributes for GETTER_METHODS_ONLY. So that means it won't attempt to generate attributes which read directly from fields. 

The second issue is that your fields are private, and CQEngine can't generate bytecode which reads from private fields. That's because the bytecode is generated in a synthetic subclass of your class, and subclasses cannot access private fields in superclasses in Java.

Your options are:
* Keep your fields private and add public getter methods which read from those private fields, OR
* Make the fields package-private or protected instead, and then request attributes to be generated for FIELDS_ONLY (or ALL_MEMBERS).

Hope that helps!
Niall
