### ISSUE TITLE
Bug in AttributeOrdersComparator

### ISSUE THREAD

**Issue by ivanantipin** [npgall/cqengine#305]
line 92: return o1.hashCode() >= o2.hashCode() ? 1 : -1;

if you have 3 objects in collection with same hashCode then:

a > b > c > a - which is not correct

and generally may throw an exception while ordering result

**Comment by ivanantipin** [comment]
oh, missed that
I would change :

 // No differences found according to ordering specified, but in case this comparator
        // will be used for object equality testing, return 0 only if objects really are equal...
        if (o1.equals(o2)) {
            return 0;
        }

why do not fallback to just "return 0" without checking for equality ?

**Comment by ivanantipin** [comment]
I have around 8k collection to sort by timestamp (long) - so not very convenient to give an example to reproduce
it is just confusing that equal/hashcode has side effect on  ordering  functionality by timestamp
for sure bytearray field need to be treated specially for equals/hashcode - i have fixed that, 
maybe this is minor , but still in my opinion it is a bug , so when you sort arraylist this shall not use this part of functionality when you need to call equals / hashcode to find ordering

**Comment by npgall** [comment]
I will close this. I don't think this is a bug in CQEngine. It's an intentional tradeoff that is already well documented in the source code.

For applications where this is an issue, the best solution is to add a "tie-breaker" attribute into the list of attributes by which results should be sorted. Feel free to reopen if you'd like to discuss further.
