### ISSUE TITLE
OffHeapPersistence.onPrimaryKey doesn't allow me to use the Attribute interface

### ISSUE THREAD

**Issue by yshadow** [npgall/cqengine#44]
While using OffHeapPersistence.onPrimaryKey, I cannot use the Attribute interface as a parameter. Signature of the static method is using SimpleAttribute<O, A>, which should be IMHO Attribute<O,A>.

Thanks.

**Comment by npgall** [comment]
Thanks for taking time to report the potential issue. However this is intentional: Attributes are multi-valued by default. SimpleAttribute restricts it to return a single value for each object. And in an index a primary key must have be a single value which identifies an object. If you have any questions you can use the forum!

**Comment by yshadow** [comment]
Thank you for your response. But then, I think there is no reason for the SimpleAttribute to be part of the Attribute hierarchy. Moreover I can override the getValues method from the SimpleAttribute abstract object and most likely cause a disaster as the getValue method relies on the fact that the getValues returns a singletonList. And you can get rid off this a bit cumbersome code (SimpleQuery): 
```java
if (attribute instanceof SimpleAttribute) {
    this.attributeIsSimple = true;
    this.simpleAttribute = (SimpleAttribute<O, A>) attribute;
}
else {
    this.attributeIsSimple = false;
    this.simpleAttribute = null;
}

But anyway thank you. This library is great.

**Comment by npgall** [comment]
Thanks yshadow. That code looks cumbersome but it is intentional though. When CQEngine is evaluating queries and an index is not available on an attribute mentioned in the query, it will ask the attribute to provide values belonging to the (potentially many) objects in turn. This code exists to reduce the amount of garbage objects created during that
