### ISSUE TITLE
Allow configuration of the NodeFactory used by InvertedRadixTreeIndex

### ISSUE THREAD

**Issue by abelunibo** [npgall/cqengine#49]
Hi, I have been following you for a while, first with the concurrent-trees project and now with this one. I think the feature of having an InvertedRadixTree in here is quite useful. However I came to a problem with this feature:

-I created a test example following your code and I found that the with the InvertedRadixTreeIndex having a collection of 5 millions of cars gives an OutOfMemory exception. Is there a workaround for this?

Furthermore, now that the InvertedRadixTree structure has the serialization feature, it could quite useful the option of saving the InvertedRadixTreeIndex to disk so we don't need to construct it again after loading the data from disk.

**Comment by npgall** [comment]
Hi abelunibo, this is a good point.

You are correct that the InvertedRadixTree from concurrent-trees allows memory usage to be reduced by supplying a different NodeFactory, but the InvertedRadixTreeIndex class in CQEngine hard codes the DefaultCharArrayNodeFactory - which uses the most memory!

There is currently no workaround, however I will try to fix this in the next version of CQEngine!
Alternatively if you'd like to submit a Pull Request it could speed it up. You can see this issue could be fixed easily by allowing the NodeFactory to be supplied to the constructor instead of being hard-coded.

Regarding serialization, I am thinking about a generic way to allow an IndexedCollection and all of its indexes to be serialized actually. I reopened issue 12 to track that.

This issue 49 will be fixed in the next release, ETA a few weeks (although pull requests welcome!).

Thanks, Niall
