### ISSUE TITLE
[Question] Android support

### ISSUE THREAD

**Issue by mttkay** [npgall/cqengine#55]
Apologies if this is not the best platform to discuss this.

I stumbled upon this project after reading about LMAX. I was immediately intrigued. Has this ever run on Android clients, or is there anything major standing in the way of making that happen?

Scanning the dependencies it appears you're depending on two persistence solutions (Kryo and SQLite--why both by the way?) both of which are compatible with Android (SQLite is natively supported and I think Kryo added Android support a while back.)

Javassist might be a problem since Android VMs do not interpret Java byte codes. Is it an essential component? Off-heap persistence might be similarly problematic I suppose, but it doesn't seem essential.

Curious what you think.

**Comment by npgall** [comment]
Hi Matthias,

Yes you are right. CQEngine's on-heap configuration *should* work okay on Android if you avoid using the on-heap or disk persistence. However I have not tested it - let me know if it does not. You can exclude the dependency on SQLite.

The problem with off-heap and disk persistence in CQEngine on Android right now is that unless something has changed recently, AFAIK Android does not provide the JDBC interfaces which are normally built into every JVM. CQEngine uses JDBC to access SQLite. So although Android has SQLite built-in, CQEngine's means of accessing it is blocked.

However this might change with Android N, because starting with Android N Google are switching to OpenJDK. So it's possible that CQEngine will become fully compatible with Android at that point.

In the meantime, if you're interested in implementing something in this area, it might not be a big deal (TBD) to write an AndroidDiskIndex or AndroidOffHeapIndex class yourself. You could take a look at the implementation of CQEngine's SQLiteIndex class and hopefully re-use a lot of that code - to adapt it to use Android's native API for accessing SQLite, or using something like [SQLDroid](https://github.com/SQLDroid/SQLDroid).

If you open source it I'd be happy to link from the CQEngine project to your project as a source of additional indexes or persistence suitable for Android. Also if you need any changes made to CQEngine itself let me know and I'd try to help.

Feel free to continue discussion on this issue here and I will respond, but I'll mark it closed now as that's the current situation.

Hope that helps,
Niall

**Comment by mttkay** [comment]
Thanks for the information--very useful.
