### ISSUE TITLE
ConcurrentIndexedCollection and HashIndexes - occasional empty retrieve resultset during async update

### ISSUE THREAD

**Issue by kimptoc** [npgall/cqengine#70]
Using a similar test to before - https://github.com/kimptoc/cqengine-test/tree/master/src/main/java/threaded/imdb2

Collection with a single object, one thread updating while another reads the same object.

Using ConcIC with HashIndex - intermittently the retrieval returns an empty set.

If I switch to the latest TransIC or use UniqueIndex - then it works fine.

Strange that using a different index affects the behaviour.

PS forgot to mention that the retrieve and update calls are sync'd in a wrapper object, so am surprised that there is an inconsistency - do indexes get updated async or perhaps the resultset is evaluated lazily?

**Comment by npgall** [comment]
This isn't a bug, it's the expected behaviour for ConcurrentIndexedCollection :)

ConcurrentIndexedCollection removes the old object before it inserts the new object. It doesn't do it atomically either. So reading threads can find these objects in some indexes but not in others, and they can actually see both objects or neither object in a ResultSet. (This is in contrast to the TransactionalIndexedCollection which is the exact opposite!)

Yes ResultSets are evaluated lazily. They don't store any results :) They traverse the indexes lazily as the application iterates through the ResultSet, returning matching objects on-the-fly.

So if you need atomicity you can either use the TransactionalIndexedCollection (for MVCC), or alternatively you can take a look at the section "Transaction Isolation without MVCC" in [TransactionIsolation.md](https://github.com/npgall/cqengine/blob/master/documentation/TransactionIsolation.md). There are instructions on that page on how you can apply locking to get atomicity from ConcurrentIndexedCollection (without MVCC).

**Comment by kimptoc** [comment]
Thanks again for clarifying :)

Strange that I don't see the problem when using UniqueIndex but I do with HashIndex.

**Comment by npgall** [comment]
You might just get this race condition with one index but not the other
because the UniqueIndex is faster to update. If you do find a problem let
me know though!
