### ISSUE TITLE
support "group by" in sql?

### ISSUE THREAD

**Issue by cycorey** [npgall/cqengine#81]
why not support "group by" in sql?

thanks!

**Comment by npgall** [comment]
Hy cycorey,

At the moment CQEngine focusses more on [OLTP](https://en.wikipedia.org/wiki/Online_transaction_processing), than [OLAP](https://en.wikipedia.org/wiki/Online_analytical_processing). If you require GROUP BY, the official documentation suggests to use [Java 8 features](https://github.com/npgall/cqengine#grouping-and-aggregation-group-by-sum) for this.

Your question doesn't really make sense to me because the SQL parser in CQEngine can't magically implement features which the underling query engine doesn't support. There is not any underlying support for aggregation in the engine, which is somehow just hidden by the SQL parser :) The SQL parser just converts SQL queries to native CQEngine queries, which are then passed to the retrieve() method.

On the other hand, _that's not the complete answer_. You may note that CQEngine's indexes implement statistical interfaces: 
* [KeyStatisticsIndex](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/index/support/KeyStatisticsIndex.html)
* [SortedKeyStatisticsIndex](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/index/support/SortedKeyStatisticsIndex.html)

**These interfaces provide the raw data to accelerate GROUP BY and DISTINCT operations.**

So at the moment you can either use Java 8/streams/lambdas, or you can use these interfaces to implement your own GROUP BY operations programmatically which can be accelerated by indexes. The second option will outperform the first, but as there is no higher-level support for it in CQEngine (yet - maybe), this approach can only be used to group by one attribute at a time.

HTH,
Niall
