### ISSUE TITLE
Any specific reason for logical query evaluation order?

### ISSUE THREAD

**Issue by yrashk** [npgall/cqengine#83]
I am looking for reasoning (if there's any) behind the order of evaluation implemented in `And` and `Or` queries: https://github.com/npgall/cqengine/blob/master/code/src/main/java/com/googlecode/cqengine/query/logical/And.java#L49-L58

Specifically, why does it evaluate simple queries first and logical ones after? My first thought was *optimization*, but I am not quite positive this is the driver behind the design.

This order went against my natural "left-to-right" expectation that is common in these kind of operators. Let's suppose I had a query like this:

```java
or(and(equal(ATTR1, 1), equal(ATTR2, 2)), matchesRegex(ATTR3, ".*"))
```

This query would have a regex match first and then equality comparison, and if I don't have a standing query index for the regex, then the performance of this query is going to be capped. If the evaluation followed the definition order, though, `matchesRegex` could have been avoided on filtered out elements.

What am I missing in this picture?

**Comment by npgall** [comment]
Hi Yuri,

In general this is an optimization, although it applies to `and()` queries more than `or()` queries. 

Basically if all simple queries are equally expensive to evaluate, and some of them are nested deep in branches of a tree, then it is cheaper to evaluate the simple queries first, because (for And queries), if any of the simple queries evaluate false, then it avoids having to evaluate the branches.

However this particular logic is only used when filtering. The CollectionQueryEngine class traverses the query tree and it will replace `And` and `Or` Query objects with `ResultSetIntersection` and `ResultSetUnion` objects. 

As the outer query in your example will be translated to a `ResultSetUnion`, I don't think the order of evaluation of the child queries really matters: for set union, it needs to evaluate all of the child nodes.

However let's say the outer query in your example was an `and()` query. _CollectionQueryEngine does have a bias towards initializing `ResultSetIntersection` to evaluate simple queries first too._

It will reorder the child queries to be intersected, such that the simple queries will be evaluated first in ascending order of their merge costs, and then the non-simple queries will be evaluated second, in ascending order of their merge costs. So technically, a branch for a non-simple query could have a lower merge cost than some of the simple queries, but the more expensive simple query would be evaluated first - a sub-optimal query plan for sure.

BUT I believe the original rationale for this, was that actually calculating the merge cost isn't entirely free. It means asking the indexes to retrieve statistics. With simple queries, there is a guarantee that only one index will be queried to calculate merge cost. Whereas calculating merge cost for non-simple queries, can mean that several indexes for the nested branches would be queried, and those merge costs need to percolate up the tree.

So it's not perfect.  I suppose as merge cost is a measure of how expensive it _would be_ to merge sets of objects together, but calculating merge cost itself isn't free, then technically CQEngine might benefit from a _meta merge cost_ which would be the estimated cost of calculating the merge costs! With meta calculations, it's [turtles all the way down](https://en.wikipedia.org/wiki/Turtles_all_the_way_down) ...

**Comment by npgall** [comment]
By the way after thinking about this a bit more, I think the engine could be a bit smarter when it has to deal with the situation above. 

It should definitely calculate the merge costs of branches belonging to non-simple queries and consider evaluating those first, if it finds that no suitable indexes at all can accelerate the simple queries which are siblings.

Right now the presence of simple queries which are siblings of a branch, could cause the engine to miss the opportunity to use indexes on other simple queries in more deeply nested branches. I'll try to improve this.

**Comment by npgall** [comment]
After investigating further, it turns out that the engine actually does not have a bias toward evaluating simple queries. 

So although there is overhead in calculating merge cost, that overhead is not currently considered. I did consider this issue a few years back, but the current algorithm most likely outperformed the alternative. So unless some new reason to reconsider it appears, I will leave the current algorithm as-is.
