### ISSUE TITLE
DiskPersistence doesn't behave Set-like with remove/add

### ISSUE THREAD

**Issue by pmiddend** [npgall/cqengine#84]
I'm normally using an in-memory `ConcurrentIndexedCollection<MyObject>` (`MyObject` has a unique identifier String) which I treat like a set. For example, I replace elements with the same unique ID using

    collection.remove(element);
    collection.add(element);

In cqengine, this apparently uses `equals` when using the in-memory collection, which is conformant with the `Set` specification (see the docs for `Set.remove`). With an on-disk persistence, created as such:

    new ConcurrentIndexedCollection<MyObject>(DiskPersistence.onPrimaryKey(PRIMARY_ATTRIBUTE))

where `PRIMARY_ATTRIBUTE` is a `SimpleAttribute<MyObject,String>`, my remove/add pair doesn't work. No element is removed by the first statement. I'm not entirely sure, but it seems as if cqengine doesn't use the string resulting from `PRIMARY_ATTRIBUTE` as the (primary) key for the database table, but the whole serialized object!

I'm using version 2.7.0, by the way.

**Comment by npgall** [comment]
Hi Philipp,

Did you definitely implement MyObject.equals() and MyObject.hashCode()?

If so could you provide a test case which I can run which demonstrates the problem?

Thanks!
Niall

**Comment by pmiddend** [comment]
I definitely implemented `equals` and `hashCode`. Sorry to leave you hanging here, but since I'm on vacation the next week I'll try to provide a self-contained test-case next monday.

**Comment by npgall** [comment]
No problem.

A test like the following passes for me - maybe you could adapt it to your use case.

```java
@Test
public void testDiskPersistenceAddRemove() {
    IndexedCollection<Car> collection =
            new ConcurrentIndexedCollection<Car>(DiskPersistence.onPrimaryKey(Car.CAR_ID));

    // Add 10 cars to the collection...
    collection.addAll(CarFactory.createCollectionOfCars(10));
    Assert.assertEquals(10, collection.size());

    // Remove car 5...
    Assert.assertTrue(collection.remove(CarFactory.createCar(5)));
    Assert.assertEquals(9, collection.size());

    // Try to remove car 5 again (not stored)...
    Assert.assertFalse(collection.remove(CarFactory.createCar(5)));
    Assert.assertEquals(9, collection.size());

    // Add car 5 again...
    Assert.assertTrue(collection.add(CarFactory.createCar(5)));
    Assert.assertEquals(10, collection.size());

    // Try to add car 5 again (already stored)...
    Assert.assertFalse(collection.add(CarFactory.createCar(5)));
    Assert.assertEquals(10, collection.size());
}
```

However there's no rush! Enjoy the vacation!

**Comment by pmiddend** [comment]
Since I'm a bit stuck coming up with a self-contained example, I tried digging into the source code of cqengine a little and I have some questions about it.

So you're using both the user-defined primary key (in my case, a string) as well as the binary representation of the object as primary key of the sqlite data base (see `DBQueries.createIndexTable`). This confused me earlier. When removing an element (in `SQLiteIndex.removeAll`), however, you rely solely on the serialized representation of the object: `SQLiteIndex.objectKeyIterable` is passed `primaryKeyAttribute`, which is, however, not the string-valued attribute I passed to `DiskPersistence.onPrimaryKey`, but the Kryo-serialized binary representation of the object, see the constructor of `SQLiteIdentityIndex`.

Correct me if I'm wrong here, but doesn't this circumvent both equals/hashCode and the primary key I pass in `onPrimaryKey`?

**Comment by npgall** [comment]
Hi Philipp,

In the SQLite-related classes, the binary representation of the object is not the primary key in the database. They use the user-provided primary key to store and retrieve objects. 

When the `SQLiteIndex.removeAll` method is called to remove certain domain objects from the collection, you can see that it calls the `SQLiteIndex.objectKeyIterable` method _to transform those domain objects to a collection of their primary keys_ using the configured primary key attribute. Armed with the primary keys, the `removeAll` method then removes rows from the database via primary keys.

However _above the SQLite layer_, the engine itself often relies on `Object.equals()`/`hashCode()` to determine object equality.  So it expects that the implementation of `Object.equals()`/`hashCode()` in domain objects will be consistent with the equality as determined from primary keys.

Hope that makes sense,
Niall

**Comment by pmiddend** [comment]
Okay, so we're basically on the same page. 

You say that `SQLiteIndex.objectKeyIterable` transforms the domain objects to their (user-configured) primary keys. I don't see that. The concrete line is

    objectKeyIterable(objectSet, primaryKeyAttribute, queryOptions)

So the `primaryKeyAttribute` is passed, which I supposed was my String-based ID. Looking at how `primaryKeyAttribute` is initialized, however, I observe this in `SQLiteIdentityIndex` (it's the **second** parameter!):

    this.sqLiteIndex = new SQLiteIndex<A, O, byte[]>(
        primaryKeyAttribute,
        new SerializingAttribute(primaryKeyAttribute.getObjectType(), byte[].class),
        new DeserializingAttribute(byte[].class, primaryKeyAttribute.getObjectType()),
        "") { ...

The first parameter is my user-defined primary key. The second parameter of `SQLiteIndex` doesn't even know about that.

**Comment by npgall** [comment]
Hi Philipp,

This really is very low-level stuff in CQEngine and it's my intent that end users should never have to deal these headaches. But I'll explain what's going on AFAIK.

`SQLiteIdentityIndex` really configures the `SQLiteIndex` in a peculiar way in order to persist the entire collection.

To explain that, I'll first have to explain the *typical* usage of `SQLiteIndex` which is a bit more intuitive. But that said, even `SQLiteIndex` isn't really recommended for use directly by end users! It's really a low-level index that's leveraged internally by other more user-friendly indexes. Regardless - it's configured with 3 parameters: an `attribute`, a `primaryKeyAttribute`, and a `foreignKeyAttribute`. 

* The `attribute`, will typically be something like Car.COLOR. This is the attribute which applications deal with. Given a Car object, it will return the color of the Car. This is what we typically want to build the index on.
* The `primaryKeyAttribute` is a function which returns a value which uniquely identifies an object. Typically it will be something like Car.CAR_ID, where given a Car object, it will return the carId. 

Because the `SQLiteIndex` is off-heap, we can't store a reference to the Car object which has a particular color directly in the index, so it uses this `primaryKeyAttribute` to obtain and store a primary key for the object instead. So combined, the two attributes above provide the pair of items which we can store in the `SQLiteIndex`: [color, carId]. 

These attributes are invoked on the write path, when the index must be updated. So far so good!

* The `foreignKeyAttribute` is a reverse function which given a carId can return an actual Car object. The best way to retrieve a Car object given its carId, it to access a _different index_, on carId. So it's normally the case that when the `foreignKeyAttribute` is invoked, it will actually access a different index to retrieve the Car object. 

But configuring dependencies between indexes is complicated. It's why I say in the documentation that most users of the library should never use `SQLiteIndex` directly.

If you're interested in the details, you can see that the `SimplifiedSQLiteIndex` (which wraps the `SQLiteIndex` and is much easier to use) automatically locates an index on the primary key, and it supplies an implementation of the `foreignKeyAttribute` to the `SQLiteIndex` it wraps, which will dynamically use the index on the primary key to retrieve objects. It wires the two indexes together. This is also why it's necessary to configure CQEngine with a primary key, when you want to use any of the non-heap persistence implementations.

So that explains the *typical* usage of SQLite index.  But as I said, the `SQLiteIdentityIndex` actually configures the `SQLiteIndex` in a completely different way. 

The `SQLiteIdentityIndex` usually _is that other index on the primary key_ which other instances of `SQLiteIndex` will access via their `foreignKeyAttribute`.

So in this case it wants to configure the `SQLiteIndex` to store a pair of items [carId, \<serialized bytes of the Car object\>]. As such it supplies the `primaryKeyAttribute` it was configured with *as the `attribute` to the `SQLiteIndex` it wraps*. And effectively it supplies a serializer in place of the `primaryKeyAttribute` and a deserializer in place of the `foreignKeyAttribute`.

So long story short, my earlier post refers to the typical usage of `SQLiteIndex` and not to the use case where it's wrapped by a `SQLiteIdentityIndex`.

In the latter case, when an object is removed from the collection, AFAICS the `SQLiteIdentityIndex` will ultimately cause the object to be serialized and then it will be removed from the `SQLiteIndex` by looking up rows in that index which contain the serialized bytes. 

This isn't super-performant in the case of removals, but it's because of another requirement: the `SQLiteIdentityIndex` doesn't actually have a guarantee that the primary key will always uniquely identify one object! 

It's an edge case, but it's common: the MVCC algorithms in the `TransactionalIndexedCollection` actually require that two different versions of the same object (having the same primary key) may be stored in the collection at the same time.

So anyway hopefully this helps to explain it. As I said this is low level stuff which most users should not need to deal with - hopefully!

**Comment by pmiddend** [comment]
Wow, thank you very much for the in-depth explanation! Of course it's good that as a normal user, I don't have to worry about this stuff, but while debugging I just dug into it and was interested in how it works.

That being said, I misunderstood the primary key, and if removal depends on the serialized version of the object being equal, then I can close this issue, as it is the intended behavior.

**Comment by npgall** [comment]
No problem. It may be useful that I've documented this for my own sake in future!
