### ISSUE TITLE
Is there a known issue with removing items?

### ISSUE THREAD

**Issue by jacobg** [npgall/cqengine#91]
I just wrote a unit test for removing an item from a ConcurrentIndexedCollection, and sometimes the unit test fails because the item is not removed. In the debugger watch list, the IndexedCollection shows that the item is not there, but doing a query returns it. Do you have any ideas about this issue occurring? If not, I can spend some time writing a pared-down unit test that reproduces the issue.

In case the following information helps, I'll provide it. I have several indexes: a UniqueIndex and three NavigableIndexes. When removing the item, I look it up using the UniqueIndex, then remove that object. Afterward, I do a query using the NavigableIndexes, and that's when sometimes it returns the object.

Thanks!

**Comment by jacobg** [comment]
Ok, I was able to come up with pared-down unit tests that demonstrate the issue:
https://gist.github.com/jacobg/4d06f172206ea7a5b76489e00ae5f21c

It looks like the issue is reproduced with these steps:

1. Create a collection with a unique index and then a separate navigable index.
2. Add an item to the collection.
3. Change item property corresponding to navigable index.
4. Add item again. 

Expected result: One item in collection, and one item returned when querying on navigable index.
Actual result: One item in collection, but same item returned twice (dupe) when querying on navigable index.

Then if you remove the item, there are no items left in collection, but the query on navigable index still returns one item.

Workaround: Remove the item before changing its property. Then add it back again to collection.

**Comment by npgall** [comment]
Hi Jacobg,

This is the expected behavior actually. 

It's not really recommended to modify mutable fields in any object `Foo` stored in any collection, if the values of those fields are used in the implementation of `Foo.equals()`, `Foo.hashCode()` or `Foo.compareTo()` methods, or in the case of CQEngine _if those fields are indexed_.

**Background**
In the case of collections relying on `hashCode()` and `equals()`, to quote: _"All hash-based collections [assume that an object's hash value does not change](http://www.ibm.com/developerworks/library/j-jtp05273/) while it is in use as a key in the collection."_

In the case of collections relying on `compareTo()` (such as `SortedMap` or `NavigableMap`), similarly if a field is changed, an object may become lost in these collections, because its location in the sorted sequence may not reflect the new value of the field.

In the case of CQEngine indexes, the same applies because the values of indexed fields often _become the keys_ in other data structures which comprise the index (such as `HashIndex` or `NavigableIndex`).

**Solution**
So the recommendation with CQEngine is to use the `IndexedCollection.update()` method instead. This allows you to swap one _version_ of your object for another version which may have the modified fields.

If you need to replace objects _atomically_, in particular take a look at [TransactionalIndexedCollection.update()](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/TransactionalIndexedCollection.html#update-java.lang.Iterable-java.lang.Iterable-com.googlecode.cqengine.query.option.QueryOptions-). 

Hope that helps, somehow!
Niall

**Comment by jacobg** [comment]
Hi Nial, thanks so much for the comprehensive explanation. Yeah, I totally understand. I hadn't thought it through before. I did confirm that the `IndexedCollection.update()` solution works great.

All the best!

**Comment by npgall** [comment]
Glad to hear that. All the best too! Thanks!
